jQuery.cookie=function(b,l,i){if(arguments.length>1&&String(l)!=="[object Object]"){i=jQuery.extend({},i);if(l===null||l===void 0)i.expires=-1;if(typeof i.expires==="number"){var m=i.expires,f=i.expires=new Date;f.setDate(f.getDate()+m)}l=String(l);return document.cookie=[encodeURIComponent(b),"=",i.raw?l:encodeURIComponent(l),i.expires?"; expires="+i.expires.toUTCString():"",i.path?"; path="+i.path:"",i.domain?"; domain="+i.domain:"",i.secure?"; secure":""].join("")}i=l||{};f=i.raw?function(b){return b}:
decodeURIComponent;return(m=RegExp("(?:^|; )"+encodeURIComponent(b)+"=([^;]*)").exec(document.cookie))?f(m[1]):null};
(function(b){function l(){return function(a){if(a.jquery){var c={};c[0]=jQuery;b.map(a.jquery,function(a){var e=a[0],h=a[1],k=a[2],a=a[3];if(typeof a=="string")a=b.unsafe(a);else for(var g=0;a.length&&g<a.length;g++)a[g]=b.unsafe(a[g]);k=="call"?c[h]=c[e].apply(c[e]._obj,a):k=="attr"?(c[h]=c[e][a],c[h]?c[h]._obj=c[e]:b.debug("unrecognized")):k=="refresh"?b.refresh():b.debug("unrecognized")})}}}b.log=function(a){window.console?window.console.debug?window.console.debug(a):window.console.log&&window.console.log(a):
alert(a)};b.debug=function(a){if(b.with_default(reddit.debug,!1))return b.log(a)};b.fn.debug=function(){b.debug(b(this));return b(this)};b.redirect=function(a){window.location=a};b.fn.redirect=function(a){b(this).filter("form").find(".status").show().html("redirecting...");if(b(this).attr("target")=="_top"){for(var c=window;c!=c.parent;)c=c.parent;c.location=a}else b.redirect(a);return b(this)};b.refresh=function(){window.location.reload(!0)};b.defined=function(a){return typeof a!="undefined"};b.with_default=
function(a,c){return b.defined(a)?a:c};b.websafe=function(a){typeof a=="string"&&(a=a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/>/g,"&gt;").replace(/</g,"&lt;"));return a||""};b.unsafe=function(a){typeof a=="string"&&(a=a.replace(/&quot;/g,'"').replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&"));return a||""};b.uniq=function(a,b){for(var d=[],e={},h=b?b:a.length,k=0;k<a.length&&d.length<h;k++)e[a[k]]||(e[a[k]]=!0,d.push(a[k]));return d};(function(a,c){b.fn.show=function(c,
e){b(this).trigger("onshow");return a.call(this,c,e)};b.fn.hide=function(a,e){b(this).trigger("onhide");return c.call(this,a,e)}})(b.fn.show,b.fn.hide);var i={};b.handleResponse=l;b.request=function(a,c,d,e,h,k,g){var n=a,f=d;if(!(rate_limit(a)||window!=window.top&&!reddit.cnameframe&&!reddit.external_frame)){if(!(f=!b.with_default(e,!1)))f=i[n]?!1:i[n]=!0;e=f;c=b.with_default(c,{});d=b.with_default(d,l(n));h=b.with_default(h,"json");typeof d!="function"&&(d=l(n));f=function(a){delete i[n];return d(a)};
errorhandler_in=b.with_default(g,function(){});g=function(a){delete i[n];return errorhandler_in(a)};k=b.with_default(k,!1);if(reddit.post_site)c.r=reddit.post_site;if(reddit.cnameframe)c.cnameframe=1;if(reddit.logged)c.uh=reddit.modhash;c.renderstyle=reddit.renderstyle;e&&b.ajax({type:k?"GET":"POST",url:"/api/"+a,data:c,success:f,error:g,dataType:h})}};rate_limit=function(){var a={vote:333,comment:5E3,ignore:0,ban:0,unban:0,assignad:0},c={},d=b.defined,e=b.with_default,h=Date;return function(b){var g=
new h,f=c[b],i=e(a[b],333);c[b]=g;return d(f)&&g-f<i}}();b.fn.vote=function(a,c,d,e){if(reddit.logged&&b(this).hasClass("arrow")){var h=b(this).hasClass("up")?1:b(this).hasClass("down")?-1:0,k=b(this).all_things_by_id(),g=k.children().not(".child").find(".arrow"),f=h==1?"up":"upmod";g.filter("."+f).removeClass(f).addClass(h==1?"upmod":"up");f=h==-1?"down":"downmod";g.filter("."+f).removeClass(f).addClass(h==-1?"downmod":"down");reddit.logged&&(k.each(function(){var a=b(this).find(".entry:first, .midcol:first");
h>0?a.addClass("likes").removeClass("dislikes unvoted"):h<0?a.addClass("dislikes").removeClass("likes unvoted"):a.addClass("unvoted").removeClass("likes dislikes")}),b.defined(e)||(e=k.filter(":first").thing_id(),a+=d?"":"-"+e,b.request("vote",{id:e,dir:h,vh:a})));c&&c(k,h)}};b.fn.show_unvotable_message=function(){b(this).thing().find(".entry:first .unvotable-message").css("display","inline-block")};b.fn.thing=function(){return this.parents(".thing:first")};b.fn.all_things_by_id=function(){return this.thing().add(b.things(this.thing_id()))};
b.fn.thing_id=function(a){var a=b.with_default(a,"thing"),c=this.hasClass("thing")?this:this.thing();a!="thing"&&(c=c.find("."+a+":first"));if(c.length)return a=b.grep(c.get(0).className.match(/\S+/g),function(a){return a.match(/^id-/)}),a.length?a[0].slice(3,a[0].length):"";return""};b.things=function(){var a=b.map(arguments,function(a){return".thing.id-"+a}).join(", ");return b(a)};b.fn.same_author=function(){var a=b(this).thing_id("author"),c=[];b(".author.id-"+a).each(function(){c.push(".thing.id-"+
b(this).thing_id())});return b(c.join(", "))};b.fn.things=function(){return this.find(b.map(arguments,function(a){return".thing.id-"+a}).join(", "))};b.listing=function(a){a=a||"";if(a.slice(0,1)=="#"||a.slice(0,1)==".")a=a.slice(1,a.length);var c=a;a.slice(0,9)!="siteTable"?c="siteTable"+(a?"_"+a:""):a=a.slice(10,a.length);var d=b("#"+c).filter(":first");d.length==0&&(d=b.things(a).find(".child").append(document.createElement("div")).children(":last").addClass("sitetable").attr("id",c));return d};
var m=function(){};b.fn.set_thing_init=function(a){m=a;b(this).find(".thing:not(.stub)").each(function(){a(this)})};b.fn.new_thing_child=function(a,c){var d=this.thing_id(),e=c?b.listing(d):this.thing().find(".child:first");return(typeof a=="string"?e.prepend(a).children(":first"):a.hide().prependTo(e).show().find('input[name="parent"]').val(d).end()).randomize_ids()};b.fn.randomize_ids=function(){var a=(Math.random()+"").split(".")[1];b(this).find("*[id]").each(function(){b(this).attr("id",b(this).attr("id")+
a)}).end().find("label").each(function(){b(this).attr("for",b(this).attr("for")+a)});return b(this)};b.fn.replace_things=function(a,c,d,e){var h=this;return b.map(a,function(a){var g=a.data,a=b(h).things(g.id);e&&(a=a.filter(".stub"));if(a.length==0){var f=b.things(g.parent);f.length&&(a=b("<div></div>"),f.find(".child:first").append(a))}a.after(b.unsafe(g.content));g=a.next();c&&(g.show().children(".midcol, .entry").hide().end().children(".child:first").html(a.children(".child:first").remove().html()).end(),
d&&(a.hide(),g.children(".midcol, .entry").show()),g.find(".rank:first").html(a.find(".rank:first").html()));d?(a.hide(),c?g.children(".midcol, .entry").show():g.show()):g.hide();a.remove();m(g);return g})};b.insert_things=function(a,c){return b.map(a,function(a){var a=a.data,e=b.listing(a.parent),e=c?e.append(b.unsafe(a.content)).children(".thing:last"):e.prepend(b.unsafe(a.content)).children(".thing:first");m(e.hide().show());return e})};b.fn.delete_table_row=function(a){var c=this.parents("tr:first").get(0),
d=this.parents("table").get(0);c?b(c).fadeOut(function(){d.deleteRow(c.rowIndex);a&&a()}):a&&a()};b.fn.insert_table_rows=function(a,c){var d=this.is("table")?this.filter("table"):this.parents("table:first");b.map(d.get(),function(e){b.map(a,function(a){var d=c;d<0&&(d=Math.max(e.rows.length+d+1,0));var d=Math.min(d,e.rows.length),g=e.insertRow(d);b(g).hide().attr("id",a.id).addClass(a.css_class);b.map(a.cells,function(a){b(g.insertCell(g.cells.length)).html(b.unsafe(a))});b(g).fadeIn()})});return this};
b.fn.captcha=function(a){var b=this.find(".capimage");a&&b.attr("src","/captcha/"+a+".png").parents("form").find('input[name="iden"]').val(a);return b};b.fn.insertAtCursor=function(a){return b(this).filter("textarea").each(function(){var c=b(this).get(0),d=c.scrollTop;if(document.selection)c.focus(),document.selection.createRange().text=a;else if(c.selectionStart){var e=c.selectionStart;c.value=c.value.substring(0,c.selectionStart)+a+c.value.substring(c.selectionEnd,c.value.length);e+=a.length;c.setSelectionRange(e,
e)}else c.value+=a;if(c.scrollHeight)c.scrollTop=d;b(this).focus()}).end()};b.fn.select_line=function(a){return b(this).filter("textarea").each(function(){var c="\n",d=1,e=0;b.browser.msie&&(c="\r",d=0,e=1);for(var c=b(this).val().split(c),h=0;h<a-1;h++)e+=c[h].length+d;h=e;a<=c.length&&(h+=c[a-1].length+d);b(this).focus();this.createTextRange?(d=this.createTextRange(),d.move("character",e),e=this.createTextRange(),e.move("character",h),d.setEndPoint("StartToEnd",e),d.select()):this.selectionStart&&
this.setSelectionRange(e,h);if(this.scrollHeight)this.scrollTop=(a-2)*(this.scrollHeight/c.length)})};b.apply_stylesheet=function(a){var c=b("head").children("link[title], style[title]").filter(":first").attr("title")||"preferred stylesheet";if(document.styleSheets[0].cssText)for(var d=document.styleSheets,e=0;e<d.length;e++){if(d[e].title==c){d[e].cssText=a;break}}else b("head").children('*[title="'+c+'"]').remove(),b('<style type="text/css" media="screen"></style>').attr("title",c).text(a).appendTo("head")};
b.rehighlight_new_comments=function(){checked=b(".comment-visits-box input:checked");checked.length>0&&highlight_new_comments(checked[0].value)};var f;b.default_cookie_domain=function(a){a&&(f=a)};var j="_";b.cookie_name_prefix=function(a){a&&(j=a+"_")};b.cookie_write=function(a){if(a.name){var c={};c.expires=a.expires;c.domain=a.domain||f;c.path=a.path||"/";var d=j+a.name,a=a.data;a===null||a==""?a=null:typeof a!="string"&&(a=JSON.stringify(a));b.cookie(d,a,c)}};b.cookie_read=function(a,c){var d=
b.cookie((c||j)+a);try{d=JSON.parse(d)}catch(e){}return{name:a,data:d}}})(jQuery);
$(function(){function b(a){if(a.substring(0,1)!="#")return"#"+a;return a}function l(){m==1?($(".arrow.up").addClass("upmod").removeClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),$(".entry").removeClass("dislikes").addClass("likes")):m==-1?($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.down").addClass("downmod").removeClass("down"),$(".entry").addClass("dislikes").removeClass("likes")):($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),
$(".entry").removeClass("dislikes").removeClass("likes"))}function i(a,b,c){var d="http://www.reddit.com";b&&(d+="/r/"+b);d+="/submit?url="+encodeURIComponent(a);c&&(d+="&title="+encodeURIComponent(c));return d}reddit.external_frame=!0;var m=null;$(".arrow.up").click(function(){m=$(this).hasClass("up")?1:0;l()});$(".arrow.down").click(function(){m=$(this).hasClass("down")?-1:0;l()});var f=document.location.search;f&&f.substring(0,1)=="?"&&(f=f.slice(1,f.length));var j={};$.map(f.split("&"),function(a){a=
$.map(a.split("="),function(a){return $.websafe(decodeURIComponent(a))});j[a[0]]=a[1]});$("a").attr("href",i(j.url,j.sr,j.title));j.bgcolor&&$("body").css("background-color",b(j.bgcolor));j.bordercolor&&$(".blog").css("border-color",b(j.bordercolor));var a=j.newwindow?"_blank":"_top";$("a").attr("target",a);var c=function(){var b=i(j.url,j.sr,j.title);$(".score:visible").fadeOut(function(){$(".score").html('<a class="submit" target="'+a+'" href="'+b+'">submit</a>');$(this).fadeIn().css("display",
"")});$(".bling a, a.bling").attr("href",b);$(".arrow").each(function(){$(this).get(0).onclick=function(){a=="_blank"?window.open(b,a):window.parent.location=b}})},f={type:"GET",url:null,data:{},success:function(a){try{var b=a.data.modhash;if(b)reddit.logged=!0,reddit.modhash=b;var d=a.data.children[0].data,a=function(a){return $(".score:visible").fadeOut(function(){a();$(this).fadeIn().css("display","")})};$(".thing").addClass("id-"+d.name);$(".bling a, a.bling").attr("href","http://www.reddit.com"+
d.permalink);d.likes?(real_state=1,a(function(){$(".score.likes").html(point_label(d.score));$(".score.unvoted").html(point_label(d.score-1));$(".score.dislikes").html(point_label(d.score-2))})):d.likes==!1?(real_state=-1,a(function(){$(".score.likes").html(point_label(d.score+2));$(".score.unvoted").html(point_label(d.score+1));$(".score.dislikes").html(point_label(d.score))})):(real_state=0,a(function(){$(".score.likes").html(point_label(d.score+1));$(".score.unvoted").html(point_label(d.score));
$(".score.dislikes").html(point_label(d.score-1))}));$(".arrow").unbind("click").click(function(){$(this).vote("",set_score,!0)});reddit.logged&&m!=real_state&&(m!=null?$.request("vote",{id:d.name,dir:m}):m=real_state);l();finalize_thing(d)}catch(e){c()}},error:c},d="/button_info.json";j.sr&&(d="/r/"+j.sr+d);var e="https:"==document.location.protocol;$.cookie_read("session","reddit_").data?(f.url=d,f.dataType="json"):(f.url=(e?"https://ssl.reddit.com":"http://buttons.reddit.com")+d,f.dataType=f.jsonp=
"jsonp",f.jsonpCallback="buttonInfoCb",f.cache=!0);if($.defined(j.url))f.data.url=j.url;if($.defined(j.id))f.data.id=j.id;e||$.ajax(f)});function point_label(b){return b}function set_score(){}function finalize_thing(){};
