(function(f){var h=navigator.userAgent;if(/MSIE [67]/i.test(h)&&!f.documentMode&&!/omBrowser/.test(h)){var k=function(){try{var h=f.body,l=h.firstChild,c=f.createElement("div");c.innerHTML='<div class="Contact Dave Artz if you have a problem with this banner" style="clear: both; height: 59px; padding:0; margin:0; position: relative; text-align: center"><a href="http://browsers.aol.com/customie/aol/download.html?ocid=ie6_countdown_bannercode"><img src="http'+("http:"===location.protocol?"://o":"s://s")+
'.aolcdn.com/os/aol/aol-ie6-countdown.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div>';h.insertBefore(c.firstChild,l)}catch(n){setTimeout(k,500)}};k()}})(document);
(function(f,h){var k=function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},j=/^[\],:{}\s]*$/,l=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,c=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,n=/(?:^|:|,)(?:\s*\[)+/g;f.Aol||(Aol={});Aol.bind=function(a,c,f){a.attachEvent?a.attachEvent("on"+c,f):a.addEventListener&&a.addEventListener(c,f,!1)};Aol.unbind=function(a,c,f){a.detachEvent?a.detachEvent("on"+c,f):a.removeEventListener&&a.removeEventListener(c,f,!1)};Aol.get=function(a,
c){c=c||h;return"#"===a.charAt(0)?c.getElementById(a.substr(1)):c.getElementsByTagName(a)};Aol.trim=k;Aol.stripTags=function(a){return a.replace(/<[^>]*>/g,"")};Aol.isArray=function(a){return-1!==a.constructor.toString().indexOf("Array")};Aol.isObject=function(a){return"object"===typeof a};Aol.isString=function(a){return"string"===typeof a};Aol.isFunction=function(a){return"function"===typeof a};Aol.isNumber=function(a){return"number"===typeof a};Aol.toQueryString=function(a,c){var f=[],h,j=encodeURIComponent,
c=c||"&";for(h in a)a.hasOwnProperty(h)&&f.push(j(h)+"="+j(a[h]));return f.length?c+f.join("&"):""};Aol.parseJSON=function(a){if("string"!==typeof a||!a)return null;a=k(a);if(f.JSON&&f.JSON.parse)return f.JSON.parse(a);if(j.test(a.replace(l,"@").replace(c,"]").replace(n,"")))return(new Function("return "+a))();f.console&&console.log("Bad JSON: "+a)}})(window,document);
(function(f,h){window[f]||(window[f]={});var k=h.plugins,j,l,c,n=parseInt;window[f].flashDetect=function(){if(!j)if(k&&(l=k["Shockwave Flash"])){if((c=l.description)&&h.mimeTypes&&h.mimeTypes["application/x-shockwave-flash"]&&h.mimeTypes["application/x-shockwave-flash"].enabledPlugin)c=c.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),j=[n(c.replace(/^(.*)\..*$/,"$1"),10),n(c.replace(/^.*\.(.*)\s.*$/,"$1"),10),/[a-zA-Z]/.test(c)?n(c.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0]}else if(window.ActiveXObject)try{if(l=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))if(c=l.GetVariable("$version"))c=c.split(" ")[1].split(","),j=[n(c[0],10),n(c[1],10),n(c[2],10)]}catch(a){}return j}})("Aol",navigator);
(function(f,h,k){if(!f.bN){var j=function(){return(new Date).getTime()},l=j(),c=encodeURIComponent,n=Aol.bind,a=Aol.get,v=Aol.trim,A=Aol.stripTags,L=Aol.isArray,E=Aol.isObject,F=Aol.isString,M=Aol.isNumber,q=Aol.toQueryString,N=Aol.parseJSON,O=[],r,G=100,P=h.title,Q=h.referrer,H=f.location,p=H.hostname,t={},u={},w=[],I=0,B=a("iframe"),R=function(){I=j()-l;J&&function(d,b){var c,f=d.length,e,g,h;for(c=0;c<f;c++){h=-1==b.indexOf(".")?c.toString():b+c;try{e=d[c].contentWindow.document,e.__bNframe=h,
n(e,"click",o.click),g=a("iframe",e),0<g.length&&arguments.callee(g,h+".")}catch(j){}}}(B,"");o.set("kb",Math.round(a("html")[0].innerHTML.length/1024))},C=1,S=function(d){var b,c=j();do if(b=j(),C)break;while(b-c<d)},D=function(d,b){var a=j(),f=new Image,a="?ts="+a+"&h="+c(p)+"&v="+o.v+"&t="+c(P)+"&r="+c(Q)+"&l="+I+"&k="+(navigator.cookieEnabled?1:0)+"&ms="+(a-l);f.onload=function(){C=1};C=0;a=["http"+("http:"===H.protocol?"://":"s://"),r,"/",d,a,b,q(t),q(u)].join("");f.src=a;u={};!h.all&&"click"===
d&&-1===b.indexOf("%23")&&-1===b.indexOf("javascript%3A")&&-1===b.indexOf("&tag=")&&S(G)},J=1,K=function(d){var b=O.toString(),c=RegExp(p+"![0-9]+"),a,e=d||f.bN_cfg||0,g,j=1,d=1;if(e){if(e.d)l=e.d;e.h&&(b+=e.h.toString());if(e.b)r=e.b;e.p&&o.set(e.p);if(e.w)G=e.w;0==e.view&&(j=0);0==e.click&&(d=0);0==e.iframes&&(J=0)}if(-1!==b.indexOf(p)&&(r||(e=p.split("."),g=e.length-1,e="localhost"===p||/\d{1,3}/.test(e[g])?"aol.com":e[g-1]+"."+e[g],r="b."+e),a=(a=b.match(c))?parseInt(a[0].replace(p+"!",""),10):
0,0===Math.floor(Math.random()*a)))if(n(f,"load",R),d&&n(h,"click",o.click),(b=Aol.flashDetect())&&o.set("fv",b[0]+"."+b[1]),t.dL_ch)j&&o.view();else{var k=0,m;(function(){if(m=f.s_265){var b={dL_ch:m.channel,dL_dpt:m.prop1,dL_sDpt:m.prop2,dL_cmsID:m.prop9},c,d;for(d in b)b.hasOwnProperty(d)&&(c=b[d])&&o.set(d,c);j&&o.view()}else 20===++k?(o.set("omniTimeOut",1),j&&o.view()):setTimeout(arguments.callee,500)})()}},o={v:14,view:function(d){d&&(d=q(d));D("vanity/",d)},click:function(d){var d=d||f.event,
b=d.srcElement||d.target||d,a,n=h.body,e=h.documentElement,g,l,k,m,p,q,i="",s="",r=0,t=0,u,x=[],y=0;if(b){F(b)&&(b=h.getElementById(b));for(a=b;b&&"HTML"!==b.nodeName;){g=b.nodeName;if(m=b.getAttribute("data-beacon"))m=N(m),(u=m.p)&&x.push(u);if(b.className&&-1!==b.className.indexOf("bN")&&(i+="&tag="+g,(l=b.innerHTML)&&(l=A(l))))i+="."+v(l);if("IMG"===g)i+="&img="+c(b.src),(m=b.alt)&&(i+="&alt="+c(v(m)));if("A"===g&&(m=b.href)){if(-1!==m.indexOf("everydayhealth.com")){var z=m.match(/aolcat=(\w*)/),
w=new Image,z=z?z[1]:"HLT";w.src="http://tacoda.at.atwola.com/rtx/r.gif?cmd="+z+"&si=18294&pi=L&xs=3&pu="+c(m)+"&r=&df=1&v=5.5&cb="+j()}i+="&ah="+c(m);if((p=b.innerHTML)&&(p=A(p)))i+="&at="+c(v(p))}if("BUTTON"===g||"INPUT"===g&&(k=b.type)&&("button"===k||"submit"===k||"image"===k)){i+="&btn="+g;if(k=b.type)i+="."+c(k);if(g=b.name)i+="."+c(g);if(g=b.value)i+="."+c(v(g));if((q=b.innerHTML)&&(q=A(q)))i+="."+c(v(q))}s+=b.id?b.id+"+":"";b=b.parentNode}if(""!==i){if(x.length)for(b=x.length;y<b;y++)x[y]._c=
1,o.set(x[y]);if(d.pageX||d.pageY)r=d.pageX,t=d.pageY;else if(d.clientX||d.clientY)r=d.clientX+n.scrollLeft+e.scrollLeft,t=d.clientY+n.scrollTop+e.scrollTop;i+="&cx="+r+"&cy="+t;d=a.ownerDocument;if(h!==d){d=d.__bNframe;s+="iframe."+d+"+";b=-1==d.indexOf(".")?B[d]:B[d.substr(0,d.indexOf("."))];do g=b.nodeName,s+=b.id?b.id+"+":"",b=b.parentNode;while("HTML"!==g)}s&&(i+="&id="+c(s.slice(0,-1)));D("click",i)}}},ping:function(d,b,a){E(b)&&(a=b,b=k);(a=a||"")&&(a=q(a));var f=1E3*b,e=function(){D("ping",
"&nm="+c(d)+a)};w[d]&&clearInterval(w[d]);if(M(b))if(0<b)w[d]=setInterval(e,f);else return;e()},set:function(a,b,c,f){var e,g;if(E(a))if(e=a,L(e))for(g=0,a=e.length;g<a;g++)o.set(e[g][0],e[g][1],e[g][2]?1:0);else{if(e._c)f=c=1,e._c="";for(g in e)e.hasOwnProperty(g)&&o.set(g,e[g],c,f)}else F(a)&&(e=c?u:t,""===b?delete e[a]:e[a]=f&&e[a]?e[a]+("+"+b):b)},init:function(a){a.h=p;K(a)}};K();f.bN=o}})(window,document);
