'use strict';window.StackExchange={};function CTIsPlayback(){try{return parent&&parent.WebPlayer}catch(e){return!1}}if(!CTIsPlayback()&&top!=self)throw top.location.replace(document.location),$(function(){$("head").add("body").remove()}),alert("For security reasons, framing is not allowed; click OK to remove the frames."),Error();
StackExchange.init=function(){var e=function(a){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){e(a)},1E3);else{var d=document.createElement("div");d.id="noscript-padding";var g=document.createElement("div");g.id="noscript-warning";g.innerHTML=a+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(d,document.body.firstChild);document.body.appendChild(g)}},a=function(){$(document).keyup(function(a){27==a.which&&
($("#lightbox:not(.no-esc-remove), .error-notification, .popup, .share-tip, .esc-remove").fadeOutAndRemove(),$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide())})},c=function(){var a=$("#hlinks"),d=$("#search input[name=q]"),g=d.width(),c=2.5*g,e,k=function(a){d.queue("expand",a)},h=!1,l=!("placeholder"in document.createElement("input"));l&&!StackExchange.options.isMobile&&(""==d[0].value&&(d[0].value="search"),d.bind({focus:function(){"search"==
this.value&&(this.value="")}}));d.keydown(function(g){if(h||46>g.keyCode&&8!=g.keyCode&&32!=g.keyCode)return!0;h=!0;clearTimeout(e);d.clearQueue("expand");k(function(g){d[0].placeholder="";a.fadeOut(100,g)});k(function(a){d.animate({width:c,"max-width":c},100,a)});k(function(){0==d.parent().find(".search-prompt").length&&d.before('<span class="search-prompt">search:</span>')});3==d.queue("expand").length&&d.dequeue("expand")}).focusout(function(){e=setTimeout(function(){k(function(a){d.parent().find(".search-prompt").remove();
a()});k(function(a){d.animate({width:g,"max-width":g},100,a)});k(function(g){l&&""==d[0].value&&(d[0].value="search");d[0].placeholder="search";a.fadeIn(100,g)});3==d.queue("expand").length&&d.dequeue("expand");h=!1},200)});$("#search").keydown(function(a){if(13==a.which&&a.ctrlKey&&d.val())return window.open("/search?q="+encodeURIComponent(d.val()),"_newtab"),!1})};return function(f){StackExchange.options=f;var d=f.serverTime-(new Date).getTime()/1E3;e(f.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();
$(function(){a();c();StackExchange.using(StackExchange.options.user.isAnonymous?"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0,f.fullPostfix);var g=StackExchange.options.styleCodeAdditionalLang;g&&StackExchange.ifUsing("prettify",function(){return StackExchange.loadJsFile("third-party/prettify/additional-langs/"+g)});StackExchange.ready(function(){genuwine.init(f.user.accountId||null,f.user.inboxUnviewedCount,f.user.notificationsUnviewedCount);f.user.messages&&StackExchange.notify.showMessages(f.user.messages,
f.isMobile);f.site.globalAuthDisabled||(!f.site.isChildMeta&&f.user.isAnonymous&&gauth.checkStackAuth(f.stackAuthUrl),gauth.informStackAuth(f.stackAuthUrl));f.user.isAnonymous||profileLink.init(f.user.gravatar,f.isMobile,f.user.profileUrl+"?tab=activity",d);f.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():StackExchange.tagmenu.init();$("*[data-tracker]").track()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(e){$(function(){var a=$("#debug-messages");a.length||(a=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(e).appendTo(a)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(e){StackExchange.initialized.done(e)};if(window.serq)for(var i=0;i<window.serq.length;i++)StackExchange.ready(window.serq[i]);
(function(){var e={anonymous:"full-anon.js",loggedIn:"full.js",prettify:"prettify-full.js",pseudoModerator:"moderator.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",revisions:"revisions.js",mockups:"mockups.js",review:"review.js"},a={},c={},f,d={},g=function(a,g){return function(d){var c=
a[d];c||(c=a[d]=g(d));return c}},n=function(g){var g=a[g],d,c=$.Deferred(),e=$.when(c),f;if(g)for(d=0;d<g.length;d++)(f=g[d].call(null))&&$.isFunction(f.promise)&&(e=$.when(e,f));c.resolve();return e},j=function(){if(!f){var a=$("script[src*='/stub.js']:first");0==a.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),f="/content/js/"):f=a.attr("src").replace(/\/stub\.js.*$/,"/")}return f},k=function(a){var g=$.Deferred(),d=document.createElement("script");d.async="async";d.type=
"text/javascript";d.src=a;d.onload=d.onreadystatechange=function(a,c){if(!d.readyState||/loaded|complete/.test(d.readyState))c?g.reject():g.resolve()};d.onerror=function(){g.reject()};$("head")[0].appendChild(d);return g.promise()},h=function(a){a=e[a];return!a?$.Deferred().reject().promise():l(a)},l=g({},function(a){var g=j()+a;var c=d["js/"+a];c?a="?v="+c:(StackExchange.debug.log("no cache breaker for "+a),a="");return k(g+a)}),o=g({},function(a){function g(){(c=StackExchange[a])?n(a).done(function(){d.resolve()}):
0<e?(e--,StackExchange.debug.log("retrying "+a),setTimeout(g,20)):(StackExchange.debug.log("object "+a+" not available although file was loaded"),d.reject())}var d=$.Deferred(),c=StackExchange[a],e=3;c?d.resolve():h(a).done(g).fail(d.reject);return d.promise()}),p=$.Deferred(),q=function(a,g,d,c){if(!d&&!p.isResolved())p.done(function(){q(a,g)});else{if(d)for(var f in e)e.hasOwnProperty(f)&&(e[f]=e[f].replace(/^(full(?:-anon)?).js$/,"$1"+(c||"")+".js"));c=o(a);d?p.resolve():c=$.when(c,StackExchange.initialized);
c.done(function(){g()}).fail(function(){StackExchange.debug.log("failed to provide object "+a)});return c}};q.setCacheBreakers=function(a){for(var g in a)a.hasOwnProperty(g)&&(d[g]=a[g])};StackExchange.using=q;StackExchange.ifUsing=function(g,d,e){if("undefined"!==typeof e){if(c["u_"+e])return;c["u_"+e]=!0}StackExchange[g]?d():((e=a[g])||(e=a[g]=[]),e.push(d))};StackExchange.loadJsFile=function(a){return k(j()+a)}})();
String.prototype.format=function(){var e=this.toString();if(!arguments.length)return e;var a="string"==typeof arguments[0]?arguments:arguments[0],c;for(c in a)e=e.replace(RegExp("\\{"+c+"\\}","gi"),a[c]);return e};String.prototype.truncate=function(e,a){var c=this.toString();e&&c.length>e&&(c=c.substr(0,e)+a);return c};String.prototype.splitOnLast=function(e){e=this.lastIndexOf(e);return 0>e?[this]:[this.substr(0,e),this.substr(e)]};String.prototype.contains=function(e){return-1<this.indexOf(e)};
StackExchange.init.createJqueryExtensions=function(){var e=StackExchange.helpers;$.extend($.expr[":"],{working:function(a){a=$(a).data("working");return"undefined"!==typeof a&&a},data:function(a,c,e){c=e[3];a=$(a).data(c);switch(typeof a){case "undefined":return!1;case "boolean":return a;case "object":return null!==a}return!0}});$.fn.extend({working:function(a){return this.each(function(){$(this).data("working",a)})},track:function(){return this.each(function(){var a=$(this),c=a.is("a[href]")?a:a.find("a[href]"),
e=a.data("tracker");c.each(function(){var a=this.href.splitOnLast("#"),g=a[0];this.href=g+=(g.contains("?")?"&":"?")+e+(a[1]||"")})})},fadeOutAndRemove:function(){return this.each(function(){var a=$(this);a.fadeOut("fast",function(){a.trigger("removing").remove()})})},charCounter:function(a){return this.each(function(){var c=a.target?$(a.target):$(this).parents("form").find("span.text-counter"),f=this;$(this).bind("blur focus keyup paste",e.DelayedReaction(function(){var d=a.min,g=a.max,e=a.setIsValid||
function(){},j=f.value?f.value.replace(/\r\n/g,"\n").length:0,k=j>0.8*g?"supernova":j>0.6*g?"hot":j>0.4*g?"warm":"cool",h="";0==j?(h="enter at least "+d+" characters",e(!1)):j<d?(h=d-j+" more to go...",e(!1)):(h=g-j+" character"+(1!=g-j?"s":"")+" left",e(j<=g));c.text(h);c.hasClass(k)||c.removeClass("supernova hot warm cool").addClass(k)},100,{sliding:!0}).trigger)})},selectRange:function(a,c){return this.each(function(){if(this.setSelectionRange)this.focus(),this.setSelectionRange(a,c);else if(this.createTextRange){var e=
this.createTextRange();e.collapse(!0);e.moveEnd("character",c);e.moveStart("character",a);e.select()}})},addSpinner:function(a){return this.each(function(){e.addSpinner(this,a)})},addSpinnerAfter:function(a){return this.each(function(){$(this).after(e.getSpinnerImg(a))})},removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},showErrorPopup:function(a,c,f){return this.each(function(){e.showErrorPopup(this,a,c,f)})},center:function(){var a=this.parent();"static"===
a.css("position")&&(a=a.offsetParent());var a=a.offset(),e=$(window);this.css("position","absolute");this.css("top",(e.height()-this.height())/2+e.scrollTop()-a.top+"px");this.css("left",(e.width()-this.width())/2+e.scrollLeft()-a.left+"px");return this},helpOverlay:function(){e.bindHelpOverlayEvents(this);return this},hideHelpOverlay:function(){e.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?this.removeAttr("disabled").css("cursor","pointer").removeClass("disabled-button"):
this.attr("disabled","disabled").css("cursor","default").addClass("disabled-button");return this},disable:function(){return this.enable(!1)},loadPopup:function(a){var c=this;c.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:a.url,dataType:"html",success:function(e){var d=$(e);d.find(".popup-actions-cancel, .popup-close a").click(function(){d.fadeOutAndRemove();a.lightbox&&$("#lightbox").fadeOutAndRemove()});d.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");
a.hideDescriptions&&d.find("ul.action-list > li:not(.action-selected) .action-desc").hide();e=d.find("input:radio:not(.action-subform input)");e.closest("li").bind("hide-action",function(){var g=$(this),d=".action-subform"+(a.hideDescriptions?", .action-desc":"");g.removeClass("action-selected").find(d).slideUp("fast")}).bind("show-action",function(){var g=$(this);g.hasClass("action-selected")||(g.siblings(".action-selected").trigger("hide-action"),g.addClass("action-selected").find(".action-subform").slideDown("fast",
function(){a.subformShow&&a.subformShow($(this));if(a.subformFocusInput){var g=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);g.length&&g.focus()}}),a.hideDescriptions&&g.find(".action-desc").slideDown("fast"),a.actionSelected&&a.actionSelected(g),d.find(".popup-submit").enable())});e.click(function(){$(this).closest("li").trigger("show-action")});d.appendTo(c.parent());a.loaded&&a.loaded(d);e=function(){};if(a.subformShow){var g=d.find("li.action-selected .action-subform");
0<g.length&&(e=function(){g.each(function(){a.subformShow($(this))})})}if(a.lightbox){var n=$('<div id="lightbox"/>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");d.css("z-index",n.css("z-index")+1)}a.dontCenter||d.center().fadeIn("fast",e)},error:function(){c.parent().showErrorPopup("Unable to load popup - please try again")},complete:e.removeSpinner});return c}})};
StackExchange.helpers=function(){function e(a,d,e){for(var c=0;c<e.length;c++){var h=e[c];try{if(/\*/.test(h))for(var l=0;4>l;l++){var o=h.replace(/\*/g,f[l]),p=a.css(o);d.css(o,p)}else d.css(h,a.css(h))}catch(q){}}}function a(a,d,c,f){if(a.is(":visible")){var h=$.browser.msie?0:0.4;c()?(a.css("opacity",h+(f?0.2:0)),a.addClass("edit-field-overlayed"),c=a.prev(".actual-edit-overlay"),0==c.length&&(f=a.parent().find("span.edit-field-overlay").text(),c=a.width(),h=a.height(),c=a.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:c,height:h}),c.is("textarea,input")?(c.val(f),e(d,c,["line-height"])):c.text(f).css("line-height",h+"px").prepend("&nbsp;"),e(d,c,["font-family","font-size","text-align"]),e(a,c,["border-*-style","border-*-color","border-*-width"]),a.css({zIndex:1,position:"relative"}),c.insertBefore(a),f=a.offset().top-
c.offset().top,0!=f&&(d=parseInt(c.css("margin-top")),f=d+f,a.is("textarea")||(f=parseInt(c.prevAll(":visible").eq(0).css("margin-bottom"))+d),c.css("margin-top",f)),a=a.offset().left-c.offset().left,0!=a&&(d=parseInt(c.css("margin-left")),c.css("margin-left",d+a)))):a.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function c(a,d){$(a).find("input[type='submit']").prop("disabled",d)}var f=["left","right","top","bottom"],d={genericBindOverlayEvents:function(g,c,e){StackExchange.options.isMobile||
c.bind("keydown contextmenu",function(){d.hideHelpOverlay(g)}).focus(function(){a(g,c,e,!0)}).blur(function(){a(g,c,e)}).each(function(){a(g,c,e)})},bindHelpOverlayEvents:function(a){a.each(function(){var a=$(this);d.genericBindOverlayEvents(a,a,function(){return""===a.val()})})},hideHelpOverlay:function(a){a.css("opacity",1);a.css("filter","");a.removeClass("edit-field-overlayed")},onClickDraftSave:function(a){$(a).click(function(){var a=this.href;StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=
null;window.location.href=a});return!1});return!0},showErrorPopup:function(a,d,c,e){$(".error-notification").remove();var f=$('<div class="error-notification supernovabg"><h2>'+d+"</h2>"+(c?"":'<span class="error-close">(click on this box to dismiss)</span>')+"</div>"),l=function(){f.fadeOutAndRemove();e&&e()};$(a).append(f);f.click(l).fadeIn("fast");setTimeout(l,c?Math.max(2500,40*d.length):3E4)},removeErrorPopup:function(){$(".error-notification").fadeOutAndRemove()},addSpinner:function(a,c){$(a).append(d.getSpinnerImg(c))},
getSpinnerImg:function(a){var d=$('<img class="ajax-loader" src="/content/img/progress-dots.gif" title="loading..." alt="loading..." />');a&&d.css(a);return d},removeSpinner:function(){$("img.ajax-loader").remove()},enableSubmitButton:function(a){c(a,!1)},disableSubmitButton:function(a){c(a,!0)},loadTicks:function(a){var d;d=a?a.find(".edit-block"):$(".edit-block");0==d.find("input[name=i1l]").length&&!d.data("loading-ticks")&&(d.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(a){d.append("<input type='hidden' name='i1l' value='"+
a+"' />")},complete:function(){d.data("loading-ticks",!1)}}))},showFancyOverlay:function(a){var a=a||{},d=$("#overlay-header"),c=a.message||"",e=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==a.showClose&&(c+='<br><a class="close-overlay">close this message</a>');d.html(c).css(e).animate({opacity:"1",height:"show"},"slow",a.complete).find(".close-overlay").click(function(){d.animate({opacity:"0",height:"hide"},"fast")})},DelayedReaction:function(a,d,c){var c=c||{},e,f,l=c.always,o=function(){e=
null;a.apply(null,f)};return{trigger:function(){f=arguments;l&&l.apply(null,f);e?c.sliding&&(clearTimeout(e),e=setTimeout(o,d)):e=setTimeout(o,d)},cancel:function(){e&&(clearTimeout(e),e=null)}}},fireAndForget:function(a){$.ajax({type:"POST",url:a,async:!0})}};return d}();
function prepareEditor(e){var a=e.postfix||"",c=function(){setTimeout(function(){StackExchange.editor.initIfShown(e)},1)};if(e.onDemand){for(var f="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),d=$('<ul id="wmd-button-row'+a+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),g=0,n=0;n<f.length;n++){var j=f[n],k=/spacer/.test(j),j=$("<li id='wmd-"+j+a+
"' />").prop("className","wmd-"+(k?"spacer":"button")).css("left",25*n).appendTo(d);$("<span />").css("background-position",g+"px -20px").appendTo(j);k||(g-=20)}var h=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){h||(h=!0,d.addSpinner({"float":"right"}),StackExchange.using("editor",function(){d.remove();e.autoShowMarkdownHelp&&(e.immediatelyShowMarkdownHelp=!0);c()}))})}else StackExchange.using("editor",c)}
StackExchange.switchMobile=function(e,a){$.post("/mobile/"+e,{returnurl:a},function(a){window.location=a})};
jQuery.cookie=function(e,a,c){if("undefined"!=typeof a){c=c||{};null===a&&(a="",c.expires=-1);var f="";if(c.expires&&("number"==typeof c.expires||c.expires.toUTCString))"number"==typeof c.expires?(f=new Date,f.setTime(f.getTime()+864E5*c.expires)):f=c.expires,f="; expires="+f.toUTCString();var d=c.path?"; path="+c.path:"",g=c.domain?"; domain="+c.domain:"",c=c.secure?"; secure":"";document.cookie=[e,"=",encodeURIComponent(a),f,d,g,c].join("")}else{a=null;if(document.cookie&&""!=document.cookie){c=
document.cookie.split(";");for(f=0;f<c.length;f++)if(d=jQuery.trim(c[f]),d.substring(0,e.length+1)==e+"="){a=decodeURIComponent(d.substring(e.length+1));break}}return a}};jQuery.expr[":"].regex=function(e,a,c){var a=c[3].split(","),f=/^(data|css):/,c=a[0].match(f)?a[0].split(":")[0]:"attr",f=a.shift().replace(f,"");return RegExp(a.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(e)[c](f))};
$.extend($.expr[":"],{containsExact:function(e,a,c){return $.trim(e.innerHTML.toLowerCase())===c[3].toLowerCase()},containsExactCase:function(e,a,c){return $.trim(e.innerHTML)===c[3]},containsRegex:function(e,a,c){a=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(c[3]);return RegExp(a[1],a[2]).test($.trim(e.innerHTML))}});
$.extend({URLEncode:function(e){for(var a="",c=0,e=e.toString(),f=/(^[a-zA-Z0-9_.]*)/;c<e.length;){var d=f.exec(e.substr(c));null!=d&&1<d.length&&""!=d[1]?(a+=d[1],c+=d[1].length):(" "==e[c]?a+="+":(d=e.charCodeAt(c).toString(16),a+="%"+(2>d.length?"0":"")+d.toUpperCase()),c++)}return a},URLDecode:function(e){for(var a,c=/(%[^%]{2})/;null!=(m=c.exec(e))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),a=String.fromCharCode(b),e=e.replace(m[1],a);return e}});
(function(e){e.fn.typeWatch=function(a){function c(a){if("TEXT"==a.type.toUpperCase()||"TEXTAREA"==a.nodeName.toUpperCase()){var c={timer:null,text:e(a).val().toUpperCase(),cb:f.callback,el:a,wait:f.wait};f.highlight&&e(a).focus(function(){this.select()});var n=function(a){var d=c.wait,h=!1;13==a.keyCode&&"TEXT"==this.type.toUpperCase()&&(d=1,h=!0);clearTimeout(c.timer);c.timer=setTimeout(function(){var a=h,d=e(c.el).val();if(d.length>f.captureLength&&d.toUpperCase()!=c.text||a&&d.length>f.captureLength)c.text=
d.toUpperCase(),c.cb(d)},d)};e(a).keydown(n).bind("paste",null,function(a){a.which||n(this)})}}var f=e.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},a);return this.each(function(){c(this)})}})(jQuery);
(function(e){function a(a){var d;return a&&a.constructor==Array&&3==a.length?a:(d=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])]:(d=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(d[1]),2.55*parseFloat(d[2]),2.55*parseFloat(d[3])]:(d=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(d[1],16),parseInt(d[2],16),parseInt(d[3],16)]:
(d=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(d[1]+d[1],16),parseInt(d[2]+d[2],16),parseInt(d[3]+d[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?c.transparent:c[e.trim(a).toLowerCase()]}e.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(c,d){e.fx.step[d]=function(c){if(!c.colorInit){var f;f=c.elem;var j=d,k;do{k=e.curCSS(f,j);if(""!=k&&"transparent"!=k||e.nodeName(f,"body"))break;j="backgroundColor"}while(f=f.parentNode);
f=a(k);c.start=f;c.end=a(c.end);c.colorInit=!0}c.elem.style[d]="rgb("+[Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2]),255),0)].join()+")"}});var c={transparent:[255,255,255]}})(jQuery);
