'use strict';var Markdown={};
(function(){function m(g){return g}function j(){return!1}function q(){}function r(){}q.prototype={chain:function(g,e){var l=this[g];if(!l)throw Error("unknown hook "+g);this[g]=l===m?e:function(g){return e(l(g))}},set:function(g,e){if(!this[g])throw Error("unknown hook "+g);this[g]=e},addNoop:function(g){this[g]=m},addFalse:function(g){this[g]=j}};Markdown.HookCollection=q;r.prototype={set:function(g,e){this["s_"+g]=e},get:function(g){return this["s_"+g]}};Markdown.Converter=function(){function g(a){return a=
a.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?(?=\s|$)[ \t]*\n?[ \t]*((\n*)["(](.+?)[")][ \t]*)?(?:\n+)/gm,function(a,s,b,c,p,z){s=s.toLowerCase();H.set(s,d(b));if(p)return c;z&&t.set(s,z.replace(/"/g,"&quot;"));return""})}function e(a){a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,l);a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math)\b[^\r]*?.*<\/\2>[ \t]*(?=\n+)\n)/gm,
l);a=a.replace(/\n[ ]{0,3}((<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,l);a=a.replace(/\n\n[ ]{0,3}(<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>[ \t]*(?=\n{2,}))/g,l);return a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,l)}function l(a,b){var c;c=b.replace(/^\n+/,"");c=c.replace(/\n+$/g,"");return c="\n\n~K"+(z.push(c)-1)+"K\n\n"}function m(a,d){a=E(a);a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=a.replace(/^[ ]{0,2}([ ]?-[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=
a.replace(/^[ ]{0,2}([ ]?_[ ]?){3,}[ \t]*$/gm,"<hr />\n");a=f(a);a=F(a);a=b(a);a=e(a);return a=c(a,d)}function j(a){a=n(a);a=D(a);a=a.replace(/\\(\\)/g,I);a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,I);a=a.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,w);a=a.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,w);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,A);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?((?:\([^)]*\)|[^()\s])*?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,
A);a=a.replace(/(\[([^\[\]]+)\])()()()()()/g,A);a=i(a);a=a.replace(/~P/g,"://");a=d(a);a=a.replace(/([\W_]|^)(\*\*|__)(?=\S)([^\r]*?\S[\*_]*)\2([\W_]|$)/g,"$1<strong>$3</strong>$4");a=a.replace(/([\W_]|^)(\*|_)(?=\S)([^\r\*_]*?\S)\2([\W_]|$)/g,"$1<em>$3</em>$4");return a=a.replace(/  +\n/g," <br>\n")}function D(a){return a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--(?:|(?:[^>-]|-[^>])(?:[^-]|-[^-])*)--)>)/gi,function(a){var s=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return s=k(s,"!"==a.charAt(1)?
"\\`*_/":"\\`*_")})}function A(a,b,c,d,p,z,i,u){void 0==u&&(u="");a=c.replace(/:\/\//g,"~P");d=d.toLowerCase();if(""==p)if(""==d&&(d=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=H.get(d))p=H.get(d),void 0!=t.get(d)&&(u=t.get(d));else if(-1<b.search(/\(\s*\)$/m))p="";else return b;p=P(p);p=k(p,"*_");b='<a href="'+p+'"';""!=u&&(u=o(u),u=k(u,"*_"),b+=' title="'+u+'"');return b+(">"+a+"</a>")}function o(a){return a.replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;")}function w(a,b,c,d,p,
z,i,u){a=c;d=d.toLowerCase();u||(u="");if(""==p)if(""==d&&(d=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=H.get(d))p=H.get(d),void 0!=t.get(d)&&(u=t.get(d));else return b;a=k(o(a),"*_[]()");p=k(p,"*_");b='<img src="'+p+'" alt="'+a+'"';u=o(u);u=k(u,"*_");return b+(' title="'+u+'"')+" />"}function E(a){a=a.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,function(a,b){return"<h1>"+j(b)+"</h1>\n\n"});a=a.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(a,b){return"<h2>"+j(b)+"</h2>\n\n"});return a=a.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,
function(a,b,s){a=b.length;return"<h"+a+">"+j(s)+"</h"+a+">\n\n"})}function f(a){var a=a+"~0",b=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;p?a=a.replace(b,function(a,b,c){a=-1<c.search(/[*+-]/g)?"ul":"ol";b=y(b,a);b=b.replace(/\s+$/,"");return"<"+a+">"+b+"</"+a+">\n"}):(b=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g,a=a.replace(b,function(a,b,c,s){a=-1<s.search(/[*+-]/g)?"ul":"ol";c=y(c,a);
return b+"<"+a+">\n"+c+"</"+a+">\n"}));return a=a.replace(/~0/,"")}function y(a,b){p++;var a=a.replace(/\n{2,}$/,"\n"),c=J[b],d=!1,a=(a+"~0").replace(RegExp("(^[ \\t]*)("+c+")[ \\t]+([^\\r]+?(\\n+))(?=(~0|\\1("+c+")[ \\t]+))","gm"),function(a,b,c,s){a=s;(b=/\n\n$/.test(a))||-1<a.search(/\n{2,}/)||d?a=m(v(a),!0):(a=f(v(a)),a=a.replace(/\n$/,""),a=j(a));d=b;return"<li>"+a+"</li>\n"}),a=a.replace(/~0/g,"");p--;return a}function F(b){b=(b+"~0").replace(/(?:\n\n|^)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,
function(b,c,d){b=a(v(c));b=N(b);b=b.replace(/^\n+/g,"");b=b.replace(/\n+$/g,"");return"\n\n"+("<pre><code>"+b+"\n</code></pre>")+"\n\n"+d});return b=b.replace(/~0/,"")}function h(a){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(z.push(a)-1)+"K\n\n"}function n(b){return b=b.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(b,c,d,s){b=s.replace(/^([ \t]*)/g,"");b=b.replace(/[ \t]*$/g,"");b=a(b);b=b.replace(/:\/\//g,"~P");return c+"<code>"+b+"</code>"})}function a(a){a=a.replace(/&/g,"&amp;");
a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=k(a,"*_{}[]\\",!1)}function b(a){return a=a.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,b){var c;c=b.replace(/^[ \t]*>[ \t]?/gm,"~0");c=c.replace(/~0/g,"");c=c.replace(/^[ \t]+$/gm,"");c=m(c);c=c.replace(/(^|\n)/g,"$1  ");c=c.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,b){var c;c=b.replace(/^  /mg,"~0");return c=c.replace(/~0/g,"")});return h("<blockquote>\n"+c+"\n</blockquote>")})}function c(a,b){for(var a=a.replace(/^\n+/g,
""),a=a.replace(/\n+$/g,""),c=a.split(/\n{2,}/g),d=[],p=/~K(\d+)K/,t=c.length,i=0;i<t;i++){var u=c[i];p.test(u)?d.push(u):/\S/.test(u)&&(u=j(u),u=u.replace(/^([ \t]*)/g,"<p>"),u+="</p>",d.push(u))}if(!b){t=d.length;for(i=0;i<t;i++)for(var J=!0;J;)J=!1,d[i]=d[i].replace(/~K(\d+)K/g,function(a,b){J=!0;return z[b]})}return d.join("\n\n")}function d(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?\$!])/gi,"&lt;")}function i(a){a=a.replace(/(^|\s)(https?|ftp)(:\/\/[-A-Z0-9+&@#\/%?=~_|\[\]\(\)!:,\.;]*[-A-Z0-9+&@#\/%=~_|\[\]])($|\W)/gi,
"$1<$2$3>$4");return a=a.replace(/<((https?|ftp):[^'">\s]+)>/gi,function(a,b){return'<a href="'+b+'">'+K.plainLinkText(b)+"</a>"})}function Q(a){return a=a.replace(/~E(\d+)E/g,function(a,b){var c=parseInt(b);return String.fromCharCode(c)})}function v(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")}function N(a){if(!/\t/.test(a))return a;var b=["    ","   ","  "," "],c=0,d;return a.replace(/[\n\t]/g,function(a,p){if("\n"===a)return c=p+1,a;d=(p-c)%4;c=p+1;return b[d]})}function P(a){if(!a)return"";
var b=a.length;return a.replace(L,function(c,d){return"~D"==c?"%24":":"==c&&(d==b-1||/[0-9\/]/.test(a.charAt(d+1)))?":":"%"+c.charCodeAt(0).toString(16)})}function k(a,b,c){b="(["+b.replace(/([\[\]\\])/g,"\\$1")+"])";c&&(b="\\\\"+b);return a=a.replace(RegExp(b,"g"),I)}function I(a,b){return"~E"+b.charCodeAt(0)+"E"}var K=this.hooks=new q;K.addNoop("plainLinkText");K.addNoop("preConversion");K.addNoop("postConversion");var H,t,z,p;this.makeHtml=function(a){if(H)throw Error("Recursive call to converter.makeHtml");
H=new r;t=new r;z=[];p=0;a=K.preConversion(a);a=a.replace(/~/g,"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");a=N("\n\n"+a+"\n\n");a=a.replace(/^[ \t]+$/mg,"");a=e(a);a=g(a);a=m(a);a=Q(a);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");a=K.postConversion(a);z=t=H=null;return a};var J={ol:"\\d+[.]",ul:"[*+-]"},L=/(?:["'*()[\]:]|~D)/g}})();
(function(){var m,j,q;function r(){}function g(a){this.buttonBar=f.getElementById("wmd-button-bar"+a);this.preview=f.getElementById("wmd-preview"+a);this.input=f.getElementById("wmd-input"+a)}function e(a,b){var c=this,d=[],i=0,h="none",v,f,e,k=function(a,b){h!=a&&(h=a,b||n());!m||"moving"!=h?f=setTimeout(g,1):e=null},g=function(a){e=new l(b,a);f=void 0};this.setCommandMode=function(){h="command";n();f=setTimeout(g,0)};this.canUndo=function(){return 1<i};this.canRedo=function(){return d[i+1]?!0:!1};
this.undo=function(){c.canUndo()&&(v?(v.restore(),v=null):(d[i]=new l(b),d[--i].restore(),a&&a()));h="none";b.input.focus();g()};this.redo=function(){c.canRedo()&&(d[++i].restore(),a&&a());h="none";b.input.focus();g()};var n=function(){var c=e||new l(b);if(!c)return!1;"moving"==h?v||(v=c):(v&&(d[i-1].text!=v.text&&(d[i++]=v),v=null),d[i++]=c,d[i+1]=null,a&&a())},j=function(a){var b=!1;if(a.ctrlKey||a.metaKey)switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "y":c.redo();b=!0;break;
case "z":a.shiftKey?c.redo():c.undo(),b=!0}b&&(a.preventDefault&&a.preventDefault(),window.event&&(window.event.returnValue=!1))},t=function(a){!a.ctrlKey&&!a.metaKey&&(a=a.keyCode,33<=a&&40>=a||63232<=a&&63235>=a?k("moving"):8==a||46==a||127==a?k("deleting"):13==a?k("newlines"):27==a?k("escape"):(16>a||20<a)&&91!=a&&k("typing"))};(function(){o.addEvent(b.input,"keypress",function(a){(a.ctrlKey||a.metaKey)&&(89==a.keyCode||90==a.keyCode)&&a.preventDefault()});var a=function(){if((m||e&&e.text!=b.input.value)&&
void 0==f)h="paste",n(),g()};o.addEvent(b.input,"keydown",j);o.addEvent(b.input,"keydown",t);o.addEvent(b.input,"mousedown",function(){k("moving")});b.input.onpaste=a;b.input.ondrop=a})();g(!0);n()}function l(a,b){var c=this,d=a.input;this.init=function(){if(o.isVisible(d)&&(b||!(f.activeElement&&f.activeElement!==d)))if(this.setInputAreaSelectionStartEnd(),this.scrollTop=d.scrollTop,!this.text&&d.selectionStart||0===d.selectionStart)this.text=d.value};this.setInputAreaSelection=function(){if(o.isVisible(d))if(void 0!==
d.selectionStart&&!j)d.focus(),d.selectionStart=c.start,d.selectionEnd=c.end,d.scrollTop=c.scrollTop;else if(f.selection&&!(f.activeElement&&f.activeElement!==d)){d.focus();var a=d.createTextRange();a.moveStart("character",-d.value.length);a.moveEnd("character",-d.value.length);a.moveEnd("character",c.end);a.moveStart("character",c.start);a.select()}};this.setInputAreaSelectionStartEnd=function(){if(!a.ieCachedRange&&(d.selectionStart||0===d.selectionStart))c.start=d.selectionStart,c.end=d.selectionEnd;
else if(f.selection){c.text=o.fixEolChars(d.value);var b=a.ieCachedRange||f.selection.createRange(),h=o.fixEolChars(b.text),v="\u0007"+h+"\u0007";b.text=v;var e=o.fixEolChars(d.value);b.moveStart("character",-v.length);b.text=h;c.start=e.indexOf("\u0007");c.end=e.lastIndexOf("\u0007")-1;if(v=c.text.length-o.fixEolChars(d.value).length){for(b.moveStart("character",-h.length);v--;)h+="\n",c.end+=1;b.text=h}a.ieCachedRange&&(c.scrollTop=a.ieCachedScrollTop);a.ieCachedRange=null;this.setInputAreaSelection()}};
this.restore=function(){void 0!=c.text&&c.text!=d.value&&(d.value=c.text);this.setInputAreaSelection();d.scrollTop=c.scrollTop};this.getChunks=function(){var a=new r;a.before=o.fixEolChars(c.text.substring(0,c.start));a.startTag="";a.selection=o.fixEolChars(c.text.substring(c.start,c.end));a.endTag="";a.after=o.fixEolChars(c.text.substring(c.end));a.scrollTop=c.scrollTop;return a};this.setChunks=function(a){a.before+=a.startTag;a.after=a.endTag+a.after;this.start=a.before.length;this.end=a.before.length+
a.selection.length;this.text=a.before+a.selection+a.after;this.scrollTop=a.scrollTop};this.init()}function x(a,b,c){var d,i,h,v=function(){var a=0;window.innerHeight?a=window.pageYOffset:f.documentElement&&f.documentElement.scrollTop?a=f.documentElement.scrollTop:f.body&&(a=f.body.scrollTop);return a},e=function(){if(b.preview){var c=b.input.value;if(!(c&&c==h)){h=c;var d=(new Date).getTime(),c=a.makeHtml(c);i=(new Date).getTime()-d;z(c)}}},g=function(){d&&(clearTimeout(d),d=void 0);var a=0,a=i;3E3<
a&&(a=3E3);d=setTimeout(e,a)};this.refresh=function(a){a?(h="",e()):g()};this.processingTime=function(){return i};var k=!0,n=function(a){var c=b.preview,d=c.parentNode,t=c.nextSibling;d.removeChild(c);c.innerHTML=a;t?d.insertBefore(c,t):d.appendChild(c)},l=function(a){b.preview.innerHTML=a},j,t=function(a){if(j)return j(a);try{l(a),j=l}catch(b){j=n,j(a)}},z=function(a){var d=w.getTop(b.input)-v();b.preview&&(t(a),c());b.preview&&(b.preview.scrollTop=(b.preview.scrollHeight-b.preview.clientHeight)*
(b.preview.scrollHeight<=b.preview.clientHeight?1:b.preview.scrollTop/(b.preview.scrollHeight-b.preview.clientHeight)));if(k)k=!1;else{var i=w.getTop(b.input)-v();m?setTimeout(function(){window.scrollBy(0,i-d)},0):window.scrollBy(0,i-d)}};(function(a,b){o.addEvent(a,"input",b);a.onpaste=b;a.ondrop=b;o.addEvent(a,"keypress",b);o.addEvent(a,"keydown",b)})(b.input,g);e();b.preview&&(b.preview.scrollTop=0)}function C(a,b,c,d,i,h,e){var g,n,k,I,q,r,t,z,p,J,L,s;function B(a){M.focus();if(a.textOp){c&&c.setCommandMode();
var t=new l(b);if(!t)return;var p=t.getChunks(),i=function(){M.focus();p&&t.setChunks(p);t.restore();d.refresh()};a.textOp(p,i)||i()}a.execute&&a.execute(c)}function O(a,c){var d=a.getElementsByTagName("span")[0];c?(d.style.backgroundPosition=a.XShift+" 0px",a.onmouseover=function(){d.style.backgroundPosition=this.XShift+" -40px"},a.onmouseout=function(){d.style.backgroundPosition=this.XShift+" 0px"},m&&(a.onmousedown=function(){f.activeElement&&f.activeElement!==b.input||(b.ieCachedRange=document.selection.createRange(),
b.ieCachedScrollTop=b.input.scrollTop)}),a.isHelp||(a.onclick=function(){if(this.onmouseout)this.onmouseout();B(this);return!1})):(d.style.backgroundPosition=a.XShift+" -20px",a.onmouseover=a.onmouseout=a.onclick=function(){})}function G(a){"string"===typeof a&&(a=i[a]);return function(){a.apply(i,arguments)}}function x(){c&&(O(L,c.canUndo()),O(s,c.canRedo()))}var M=b.input;g=void 0;n=void 0;k=void 0;I=void 0;q=void 0;r=void 0;t=void 0;z=void 0;p=void 0;J=void 0;L=void 0;s=void 0;(function(){var c=
b.buttonBar,d=document.createElement("ul");d.id="wmd-button-row"+a;d.className="wmd-button-row";var d=c.appendChild(d),i=0,c=function(b,c,t,p){var s=document.createElement("li");s.className="wmd-button";s.style.left=i+"px";i+=25;var z=document.createElement("span");s.id=b+a;s.appendChild(z);s.title=c;s.XShift=t;p&&(s.textOp=p);O(s,!0);d.appendChild(s);return s},f=function(b){var c=document.createElement("li");c.className="wmd-spacer wmd-spacer"+b;c.id="wmd-spacer"+b+a;d.appendChild(c);i+=25};g=c("wmd-bold-button",
e("bold"),"0px",G("doBold"));n=c("wmd-italic-button",e("italic"),"-20px",G("doItalic"));f(1);k=c("wmd-link-button",e("link"),"-40px",G(function(a,b){return this.doLinkOrImage(a,b,!1)}));I=c("wmd-quote-button",e("quote"),"-60px",G("doBlockquote"));q=c("wmd-code-button",e("code"),"-80px",G("doCode"));r=c("wmd-image-button",e("image"),"-100px",G(function(a,b){return this.doLinkOrImage(a,b,!0)}));f(2);t=c("wmd-olist-button",e("olist"),"-120px",G(function(a,b){this.doList(a,b,!0)}));z=c("wmd-ulist-button",
e("ulist"),"-140px",G(function(a,b){this.doList(a,b,!1)}));p=c("wmd-heading-button",e("heading"),"-160px",G("doHeading"));J=c("wmd-hr-button",e("hr"),"-180px",G("doHorizontalRule"));f(3);L=c("wmd-undo-button",e("undo"),"-200px",null);L.execute=function(a){a&&a.undo()};f=/win/.test(F.platform.toLowerCase())?e("redo"):e("redomac");s=c("wmd-redo-button",f,"-220px",null);s.execute=function(a){a&&a.redo()};h&&(c=document.createElement("li"),f=document.createElement("span"),c.appendChild(f),c.className=
"wmd-button wmd-help-button",c.id="wmd-help-button"+a,c.XShift="-240px",c.isHelp=!0,c.style.right="0px",c.title=e("help"),c.onclick=h.handler,O(c,!0),d.appendChild(c));x()})();var w="keydown";j&&(w="keypress");o.addEvent(M,w,function(a){if((a.ctrlKey||a.metaKey)&&!a.altKey&&!a.shiftKey){switch(String.fromCharCode(a.charCode||a.keyCode).toLowerCase()){case "b":B(g);break;case "i":B(n);break;case "l":B(k);break;case "q":B(I);break;case "k":B(q);break;case "g":B(r);break;case "o":B(t);break;case "u":B(z);
break;case "h":B(p);break;case "r":B(J);break;case "y":B(s);break;case "z":a.shiftKey?B(s):B(L);break;default:return}a.preventDefault&&a.preventDefault();window.event&&(window.event.returnValue=!1)}});o.addEvent(M,"keyup",function(a){if(a.shiftKey&&!a.ctrlKey&&!a.metaKey&&13===(a.charCode||a.keyCode))a={},a.textOp=G("doAutoindent"),B(a)});m&&o.addEvent(M,"keydown",function(a){if(27===a.keyCode)return!1});this.setUndoRedoButtonStates=x}function D(a,b){this.hooks=a;this.getString=b}function A(a){return a.replace(/^\s*(.*?)(?:\s+"(.+)")?\s*$/,
function(a,c,d){c=c.replace(/\?.*$/,function(a){return a.replace(/\+/g," ")});c=decodeURIComponent(c);c=encodeURI(c).replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29");c=c.replace(/\?.*$/,function(a){return a.replace(/\+/g,"%2b")});d&&(d=d.trim?d.trim():d.replace(/^\s*/,"").replace(/\s*$/,""),d=d.replace(/"/g,"quot;").replace(/\(/g,"&#40;").replace(/\)/g,"&#41;").replace(/</g,"&lt;").replace(/>/g,"&gt;"));return d?c+' "'+d+'"':c})}var o={},w={},E={},f=window.document,y=window.RegExp,F=
window.navigator;m=/msie/.test(F.userAgent.toLowerCase());q=/msie 6/.test(F.userAgent.toLowerCase())||/msie 5/.test(F.userAgent.toLowerCase());j=/opera/.test(F.userAgent.toLowerCase());var h={bold:"Strong <strong> Ctrl+B",boldexample:"strong text",italic:"Emphasis <em> Ctrl+I",italicexample:"emphasized text",link:"Hyperlink <a> Ctrl+L",linkdescription:"enter link description here",linkdialog:'<p><b>Insert Hyperlink</b></p><p>http://example.com/ "optional title"</p>',quote:"Blockquote <blockquote> Ctrl+Q",
quoteexample:"Blockquote",code:"Code Sample <pre><code> Ctrl+K",codeexample:"enter code here",image:"Image <img> Ctrl+G",imagedescription:"enter image description here",imagedialog:"<p><b>Insert Image</b></p><p>http://example.com/images/diagram.jpg \"optional title\"<br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",olist:"Numbered List <ol> Ctrl+O",ulist:"Bulleted List <ul> Ctrl+U",litem:"List item",heading:"Heading <h1>/<h2> Ctrl+H",
headingexample:"Heading",hr:"Horizontal Rule <hr> Ctrl+R",undo:"Undo - Ctrl+Z",redo:"Redo - Ctrl+Y",redomac:"Redo - Ctrl+Shift+Z",help:"Markdown Editing Help"};Markdown.Editor=function(a,b,c){c=c||{};"function"===typeof c.handler&&(c={helpButton:c});c.strings=c.strings||{};c.helpButton&&(c.strings.help=c.strings.help||c.helpButton.title);var d=function(a){return c.strings[a]||h[a]},b=b||"",i=this.hooks=new Markdown.HookCollection;i.addNoop("onPreviewRefresh");i.addNoop("postBlockquoteCreation");i.addFalse("insertImageDialog");
this.getConverter=function(){return a};var n=this,v;this.run=function(){if(!v){v=new g(b);var h=new D(i,d),j=new x(a,v,function(){i.onPreviewRefresh()}),k,l;/\?noundo/.test(f.location.href)||(k=new e(function(){j.refresh();l&&l.setUndoRedoButtonStates()},v),this.textOperation=function(a){k.setCommandMode();a();n.refreshPreview()});l=new C(b,v,k,j,h,c.helpButton,d);l.setUndoRedoButtonStates();(n.refreshPreview=function(){j.refresh(!0)})()}}};r.prototype.findTags=function(a,b){var c=this,d;a&&(d=o.extendRegExp(a,
"","$"),this.before=this.before.replace(d,function(a){c.startTag+=a;return""}),d=o.extendRegExp(a,"^",""),this.selection=this.selection.replace(d,function(a){c.startTag+=a;return""}));b&&(d=o.extendRegExp(b,"","$"),this.selection=this.selection.replace(d,function(a){c.endTag=a+c.endTag;return""}),d=o.extendRegExp(b,"^",""),this.after=this.after.replace(d,function(a){c.endTag=a+c.endTag;return""}))};r.prototype.trimWhitespace=function(a){var b,c=this;a?a=b="":(a=function(a){c.before+=a;return""},b=
function(a){c.after=a+c.after;return""});this.selection=this.selection.replace(/^(\s*)/,a).replace(/(\s*)$/,b)};r.prototype.skipLines=function(a,b,c){void 0===a&&(a=1);void 0===b&&(b=1);a++;b++;var d,i;navigator.userAgent.match(/Chrome/)&&"X".match(/()./);this.selection=this.selection.replace(/(^\n*)/,"");this.startTag+=y.$1;this.selection=this.selection.replace(/(\n*$)/,"");this.endTag+=y.$1;this.startTag=this.startTag.replace(/(^\n*)/,"");this.before+=y.$1;this.endTag=this.endTag.replace(/(\n*$)/,
"");this.after+=y.$1;if(this.before){for(d=i="";a--;)d+="\\n?",i+="\n";c&&(d="\\n*");this.before=this.before.replace(new y(d+"$",""),i)}if(this.after){for(d=i="";b--;)d+="\\n?",i+="\n";c&&(d="\\n*");this.after=this.after.replace(new y(d,""),i)}};o.isVisible=function(a){if(window.getComputedStyle)return"none"!==window.getComputedStyle(a,null).getPropertyValue("display");if(a.currentStyle)return"none"!==a.currentStyle.display};o.addEvent=function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,
c,!1)};o.removeEvent=function(a,b,c){a.detachEvent?a.detachEvent("on"+b,c):a.removeEventListener(b,c,!1)};o.fixEolChars=function(a){a=a.replace(/\r\n/g,"\n");return a=a.replace(/\r/g,"\n")};o.extendRegExp=function(a,b,c){if(null===b||void 0===b)b="";if(null===c||void 0===c)c="";var a=a.toString(),d,a=a.replace(/\/([gim]*)$/,function(a,b){d=b;return""}),a=a.replace(/(^\/|\/$)/g,"");return new y(b+a+c,d)};w.getTop=function(a,b){var c=a.offsetTop;if(!b)for(;a=a.offsetParent;)c+=a.offsetTop;return c};
w.getHeight=function(a){return a.offsetHeight||a.scrollHeight};w.getWidth=function(a){return a.offsetWidth||a.scrollWidth};w.getPageSize=function(){var a,b,c,d;self.innerHeight&&self.scrollMaxY?(a=f.body.scrollWidth,b=self.innerHeight+self.scrollMaxY):f.body.scrollHeight>f.body.offsetHeight?(a=f.body.scrollWidth,b=f.body.scrollHeight):(a=f.body.offsetWidth,b=f.body.offsetHeight);self.innerHeight?(c=self.innerWidth,d=self.innerHeight):f.documentElement&&f.documentElement.clientHeight?(c=f.documentElement.clientWidth,
d=f.documentElement.clientHeight):f.body&&(c=f.body.clientWidth,d=f.body.clientHeight);a=Math.max(a,c);b=Math.max(b,d);return[a,b,c,d]};E.createBackground=function(){var a=f.createElement("div"),b=a.style;a.className="wmd-prompt-background";b.position="absolute";b.top="0";b.zIndex="1000";m?b.filter="alpha(opacity=50)":b.opacity="0.5";var c=w.getPageSize();b.height=c[1]+"px";m?(b.left=f.documentElement.scrollLeft,b.width=f.documentElement.clientWidth):(b.left="0",b.width="100%");f.body.appendChild(a);
return a};E.prompt=function(a,b,c){var d,i;void 0===b&&(b="");var h=function(a){27===(a.charCode||a.keyCode)&&e(!0)},e=function(a){o.removeEvent(f.body,"keydown",h);var b=i.value;a?b=null:(b=b.replace(/^http:\/\/(https?|ftp):\/\//,"$1://"),/^(?:https?|ftp):\/\//.test(b)||(b="http://"+b));d.parentNode.removeChild(d);c(b);return!1},g=function(){d=f.createElement("div");d.className="wmd-prompt-dialog";d.style.padding="10px;";d.style.position="fixed";d.style.width="400px";d.style.zIndex="1001";var c=
f.createElement("div");c.innerHTML=a;c.style.padding="5px";d.appendChild(c);var c=f.createElement("form"),k=c.style;c.onsubmit=function(){return e(!1)};k.padding="0";k.margin="0";k.cssFloat="left";k.width="100%";k.textAlign="center";k.position="relative";d.appendChild(c);i=f.createElement("input");i.type="text";i.value=b;k=i.style;k.display="block";k.width="80%";k.marginLeft=k.marginRight="auto";c.appendChild(i);var g=f.createElement("input");g.type="button";g.onclick=function(){return e(!1)};g.value=
"OK";k=g.style;k.margin="10px";k.display="inline";k.width="7em";var n=f.createElement("input");n.type="button";n.onclick=function(){return e(!0)};n.value="Cancel";k=n.style;k.margin="10px";k.display="inline";k.width="7em";c.appendChild(g);c.appendChild(n);o.addEvent(f.body,"keydown",h);d.style.top="50%";d.style.left="50%";d.style.display="block";q&&(d.style.position="absolute",d.style.top=f.documentElement.scrollTop+200+"px",d.style.left="50%");f.body.appendChild(d);d.style.marginTop=-(w.getHeight(d)/
2)+"px";d.style.marginLeft=-(w.getWidth(d)/2)+"px"};setTimeout(function(){g();var a=b.length;if(void 0!==i.selectionStart)i.selectionStart=0,i.selectionEnd=a;else if(i.createTextRange){var c=i.createTextRange();c.collapse(!1);c.moveStart("character",-a);c.moveEnd("character",a);c.select()}i.focus()},0)};var n=D.prototype;n.prefixes="(?:\\s{4,}|\\s*>|\\s*-\\s+|\\s*\\d+\\.|=|\\+|-|_|\\*|#|\\s*\\[[^\n]]+\\]:)";n.unwrap=function(a){var b=new y("([^\\n])\\n(?!(\\n|"+this.prefixes+"))","g");a.selection=
a.selection.replace(b,"$1 $2")};n.wrap=function(a,b){this.unwrap(a);var c=new y("(.{1,"+b+"})( +|$\\n?)","gm"),d=this;a.selection=a.selection.replace(c,function(a,b){return(new y("^"+d.prefixes,"")).test(a)?a:b+"\n"});a.selection=a.selection.replace(/\s+$/,"")};n.doBold=function(a,b){return this.doBorI(a,b,2,this.getString("boldexample"))};n.doItalic=function(a,b){return this.doBorI(a,b,1,this.getString("italicexample"))};n.doBorI=function(a,b,c,d){a.trimWhitespace();a.selection=a.selection.replace(/\n{2,}/g,
"\n");var h=/(\**$)/.exec(a.before)[0],b=/(^\**)/.exec(a.after)[0],h=Math.min(h.length,b.length);h>=c&&(2!=h||1!=c)?(a.before=a.before.replace(y("[*]{"+c+"}$",""),""),a.after=a.after.replace(y("^[*]{"+c+"}",""),"")):!a.selection&&b?(a.after=a.after.replace(/^([*_]*)/,""),a.before=a.before.replace(/(\s?)$/,""),a.before=a.before+b+y.$1):(!a.selection&&!b&&(a.selection=d),c=1>=c?"*":"**",a.before+=c,a.after=c+a.after)};n.stripLinkDefs=function(a,b){return a=a.replace(/^[ ]{0,3}\[(\d+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|$)/gm,
function(a,d,h,e,g){b[d]=a.replace(/\s*$/,"");return e?(b[d]=a.replace(/["(](.+?)[")]$/,""),e+g):""})};n.addLinkDef=function(a,b){var c=0,d={};a.before=this.stripLinkDefs(a.before,d);a.selection=this.stripLinkDefs(a.selection,d);a.after=this.stripLinkDefs(a.after,d);var h="",e=/(\[)((?:\[[^\]]*\]|[^\[\]])*)(\][ ]?(?:\n[ ]*)?\[)(\d+)(\])/g,g=function(a){c++;a=a.replace(/^[ ]{0,3}\[(\d+)\]:/,"  ["+c+"]:");h+="\n"+a},f=function(a,b,h,i,t,z){h=h.replace(e,f);return d[t]?(g(d[t]),b+h+i+c+z):a};a.before=
a.before.replace(e,f);b?g(b):a.selection=a.selection.replace(e,f);var n=c;a.after=a.after.replace(e,f);a.after&&(a.after=a.after.replace(/\n*$/,""));a.after||(a.selection=a.selection.replace(/\n*$/,""));a.after+="\n\n"+h;return n};n.doLinkOrImage=function(a,b,c){a.trimWhitespace();a.findTags(/\s*!?\[/,/\][ ]?(?:\n[ ]*)?(\[.*?\])?/);var d;if(1<a.endTag.length&&0<a.startTag.length)a.startTag=a.startTag.replace(/!?\[/,""),a.endTag="",this.addLinkDef(a,null);else if(a.selection=a.startTag+a.selection+
a.endTag,a.startTag=a.endTag="",/\n\n/.test(a.selection))this.addLinkDef(a,null);else{var h=this,e=function(e){d.parentNode.removeChild(d);null!==e&&(a.selection=(" "+a.selection).replace(/([^\\](?:\\\\)*)(?=[[\]])/g,"$1\\").substr(1),e=" [999]: "+A(e),e=h.addLinkDef(a,e),a.startTag=c?"![":"[",a.endTag="]["+e+"]",a.selection||(a.selection=c?h.getString("imagedescription"):h.getString("linkdescription")));b()};d=E.createBackground();c?this.hooks.insertImageDialog(e)||E.prompt(this.getString("imagedialog"),
"http://",e):E.prompt(this.getString("linkdialog"),"http://",e);return!0}};n.doAutoindent=function(a){var b=!1;a.before=a.before.replace(/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ ]{0,3}>[ \t]*\n$/,"\n\n");a.before=a.before.replace(/(\n|^)[ \t]+\n$/,"\n\n");!a.selection&&!/^[ \t]*(?:\n|$)/.test(a.after)&&(a.after=a.after.replace(/^[^\n]*/,function(b){a.selection=b;return""}),b=!0);/(\n|^)[ ]{0,3}([*+-]|\d+[.])[ \t]+.*\n$/.test(a.before)&&this.doList&&this.doList(a);
/(\n|^)[ ]{0,3}>[ \t]+.*\n$/.test(a.before)&&this.doBlockquote&&this.doBlockquote(a);/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&this.doCode&&this.doCode(a);b&&(a.after=a.selection+a.after,a.selection="")};n.doBlockquote=function(a){a.selection=a.selection.replace(/^(\n*)([^\r]+?)(\n*)$/,function(b,c,d,e){a.before+=c;a.after=e+a.after;return d});a.before=a.before.replace(/(>[ \t]*)$/,function(b,c){a.selection=c+a.selection;return""});a.selection=a.selection.replace(/^(\s|>)+$/,"");a.selection=a.selection||
this.getString("quoteexample");var b="",c="",d;if(a.before){for(var h=a.before.replace(/\n$/,"").split("\n"),e=!1,g=0;g<h.length;g++){var f=!1;d=h[g];e=e&&0<d.length;/^>/.test(d)?(f=!0,!e&&1<d.length&&(e=!0)):f=/^[ \t]*$/.test(d)?!0:e;f?b+=d+"\n":(c+=b+d,b="\n")}/(^|\n)>/.test(b)||(c+=b,b="")}a.startTag=b;a.before=c;a.after&&(a.after=a.after.replace(/^\n?/,"\n"));a.after=a.after.replace(/^(((\n|^)(\n[ \t]*)*>(.+\n)*.*)+(\n[ \t]*)*)/,function(b){a.endTag=b;return""});b=function(b){var c=b?"> ":"";
a.startTag&&(a.startTag=a.startTag.replace(/\n((>|\s)*)\n$/,function(a,b){return"\n"+b.replace(/^[ ]{0,3}>?[ \t]*$/gm,c)+"\n"}));a.endTag&&(a.endTag=a.endTag.replace(/^\n((>|\s)*)\n/,function(a,b){return"\n"+b.replace(/^[ ]{0,3}>?[ \t]*$/gm,c)+"\n"}))};/^(?![ ]{0,3}>)/m.test(a.selection)?(this.wrap(a,70),a.selection=a.selection.replace(/^/gm,"> "),b(!0),a.skipLines()):(a.selection=a.selection.replace(/^[ ]{0,3}> ?/gm,""),this.unwrap(a),b(!1),!/^(\n|^)[ ]{0,3}>/.test(a.selection)&&a.startTag&&(a.startTag=
a.startTag.replace(/\n{0,2}$/,"\n\n")),!/(\n|^)[ ]{0,3}>.*$/.test(a.selection)&&a.endTag&&(a.endTag=a.endTag.replace(/^\n{0,2}/,"\n\n")));a.selection=this.hooks.postBlockquoteCreation(a.selection);/\n/.test(a.selection)||(a.selection=a.selection.replace(/^(> *)/,function(b,c){a.startTag+=c;return""}))};n.doCode=function(a){var b=/\S[ ]*$/.test(a.before);if(!/^[ ]*\S/.test(a.after)&&!b||/\n/.test(a.selection)){a.before=a.before.replace(/[ ]{4}$/,function(b){a.selection=b+a.selection;return""});var c=
b=1;/(\n|^)(\t|[ ]{4,}).*\n$/.test(a.before)&&(b=0);/^\n(\t|[ ]{4,})/.test(a.after)&&(c=0);a.skipLines(b,c);a.selection?/^[ ]{0,3}\S/m.test(a.selection)?/\n/.test(a.selection)?a.selection=a.selection.replace(/^/gm,"    "):a.before+="    ":a.selection=a.selection.replace(/^[ ]{4}/gm,""):(a.startTag="    ",a.selection=this.getString("codeexample"))}else a.trimWhitespace(),a.findTags(/`/,/`/),!a.startTag&&!a.endTag?(a.startTag=a.endTag="`",a.selection||(a.selection=this.getString("codeexample"))):a.endTag&&
!a.startTag?(a.before+=a.endTag,a.endTag=""):a.startTag=a.endTag=""};n.doList=function(a,b,c){var b=/^\n*(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*/,d="-",e=1,h=function(){var a;c?(a=" "+e+". ",e++):a=" "+d+" ";return a},g=function(a){void 0===c&&(c=/^\s*\d/.test(a));return a=a.replace(/^[ ]{0,3}([*+-]|\d+[.])\s/gm,function(){return h()})};a.findTags(/(\n|^)*[ ]{0,3}([*+-]|\d+[.])\s+/,null);a.before&&!/\n$/.test(a.before)&&!/^\n/.test(a.startTag)&&
(a.before+=a.startTag,a.startTag="");if(a.startTag){var f=/\d+[.]/.test(a.startTag);a.startTag="";a.selection=a.selection.replace(/\n[ ]{4}/g,"\n");this.unwrap(a);a.skipLines();f&&(a.after=a.after.replace(b,g));if(c==f)return}var n=1;a.before=a.before.replace(/(\n|^)(([ ]{0,3}([*+-]|\d+[.])[ \t]+.*)(\n.+|\n{2,}([*+-].*|\d+[.])[ \t]+.*|\n{2,}[ \t]+\S.*)*)\n*$/,function(a){/^\s*([*+-])/.test(a)&&(d=y.$1);n=/[^\n]\n\n[^\n]/.test(a)?1:0;return g(a)});a.selection||(a.selection=this.getString("litem"));
var f=h(),l=1;a.after=a.after.replace(b,function(a){l=/[^\n]\n\n[^\n]/.test(a)?1:0;return g(a)});a.trimWhitespace(!0);a.skipLines(n,l,!0);a.startTag=f;b=f.replace(/./g," ");this.wrap(a,72-b.length);a.selection=a.selection.replace(/\n/g,"\n"+b)};n.doHeading=function(a){a.selection=a.selection.replace(/\s+/g," ");a.selection=a.selection.replace(/(^\s+|\s+$)/g,"");if(a.selection){var b=0;a.findTags(/#+[ ]*/,/[ ]*#+/);/#+/.test(a.startTag)&&(b=y.lastMatch.length);a.startTag=a.endTag="";a.findTags(null,
/\s?(-+|=+)/);/=+/.test(a.endTag)&&(b=1);/-+/.test(a.endTag)&&(b=2);a.startTag=a.endTag="";a.skipLines(1,1);b=0==b?2:b-1;if(0<b){var b=2<=b?"-":"=",c=a.selection.length;72<c&&(c=72);for(a.endTag="\n";c--;)a.endTag+=b}}else a.startTag="## ",a.selection=this.getString("headingexample"),a.endTag=" ##"};n.doHorizontalRule=function(a){a.startTag="----------\n";a.selection="";a.skipLines(2,1,!0)}})();
(function(){function m(){for(var a=0;a<n.length;a++)n[a].refreshPreview()}function j(a){var b=a.match(/^\s*>\s*!/mg);if(b&&b.length==a.split("\n").length){var c=!1,a=a.replace(/(.*) (\w)/,function(a,b,d){c=!0;return b+"\n> "+d});c||(a=a.replace(/^(\s*>\s*)!/m,"$1&#33;"))}return a}function q(a){var b=/^\s*?[^\s!]/m,c=/^\s*?!/gm;return a=a.replace(/\<blockquote\>[\n\s]*?\<p\>[\n\s]*?(![\s\S]*?)\<\/p\>[\n\s]*?\<\/blockquote\>/g,function(a,d){if(b.test(d))return a;a=a.replace(d,d.replace(c,""));return a=
a.replace("<blockquote>",'<blockquote class="spoiler">')})}function r(a){for(var b="",c=[],d=[],b=a.match(/^\[section:[^\]]+?\]\s*?$/igm),d=[],e=0,h=0;h<b.length;h++){var c=b[h],f=c.indexOf(":")+1,g=c.indexOf("]",f),f=c.substr(f,g-f),f=f.replace(/^\s+/,"").replace(/\s+$/,"");0!=f.length&&(e=a.indexOf(c,e),c=c.length,d.push({index:e,length:c,title:f}),e+=c)}if(0==d.length)return c=[],d=[],{sections:[],beforeSections:a,titles:c,sectionTags:d};b=a.substr(0,d[0].index);h=function(a,b){for(var c=[],d=
0;d<a.length;d++)c.push(b(a[d]));return c};f=h(d,function(a){return a.index});c=h(d,function(a){return a.title});d=h(d,function(a){return{item1:a.index,item2:a.length}});g=[];for(h=0;h<f.length;h++)e=f[h],g.push(a.substr(e,(h+1<f.length?f[h+1]:a.length)-e));for(h=0;h<g.length;h++)if(a=/^\s+?/.exec(g[h]))0==h?b+=a:g[h-1]+=a,g[h]=g[h].substr(a.Index);return{sections:g,beforeSections:b,titles:c,sectionTags:d}}function g(a){c=[];var a=r(a),b;b=""+a.beforeSections;for(var d=0,h=0;h<a.sections.length;h++){var e=
a.sections[h],f=a.titles[h],g=a.sectionTags[h],i="\n<p>"+(1E6*Math.random()+""+ +new Date+""+1E6*Math.random())+"</p>\n";b+=i;d+=i.length;b+=e;g={item1:g.item1+d,item2:g.item2};e=b.substr(0,g.item1);b=b.substring(g.item1+g.item2);b=e+b;d-=g.item2;c.push({item1:i,item2:f})}return b}function e(a){if(0==c.length)return a;for(var b=function(a){return a.replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;").replace("'","&apos;")},d="",h=0,e=0;e<c.length;e++){var g=c[e],f=a.indexOf(g.item1.replace(/^\s+/,
"").replace(/\s+$/,"")),i;i=e+1<c.length?a.indexOf(c[e+1].item1.replace(/^\s+/,"").replace(/\s+$/,"")):a.length;d+=a.substr(h,f-h);d+='<div class="post-section" data-post-section-id="'+e+'" data-post-section-title="'+b(g.item2)+'">';d+='<p class="post-section-title">'+b(g.item2)+"</p>";d+=a.substr(f+g.item1.length,i-(f+g.item1.length));d+="</div>";h=i}return d}function l(a){if(!window.tagRendererRaw)return a;var b,c;return a=a.replace(/\[(meta-)?tag:([a-z0-9#+.-]+)\]/gi,function(d,e,g,f){if(!h&&e)return d;
if(!b){for(var i=a,n=[],l=/<(a|code)[^>]*>/ig,j;null!=(j=l.exec(i));){n.push(j.index);j=RegExp("</"+j[1]+">","ig");j.lastIndex=l.lastIndex;if(null==j.exec(i))break;n.push(j.lastIndex);l.lastIndex=j.lastIndex}b=n;c=b.length}i=!1;for(n=0;n<c&&!(b[n]>f);n++)i=!i;if(i)return d;d=null;h&&!e&&(d=F);return tagRendererRaw(sanitizeAndSplitTags(g)[0],d)})}function x(a){var b,c;"undefined"==typeof d&&(d=StackExchange.options.styleCode);d&&(b=o(a),c=o(b+a),a=E(a,b,c));a=C(a);d&&(a=f(a,b,c));return a}function C(a){return a.replace(/<[^>]*>?/gi,
D)}function D(a){return a.match(i)||a.match(Q)||a.match(v)?a:""}function A(a){if(""==a)return"";var b=/<\/?\w+[^>]*(\s|$|>)/g,c=a.toLowerCase().match(b),d=(c||[]).length;if(0==d)return a;for(var h,e,g,f=[],i=[],n=!1,j=0;j<d;j++)if(h=c[j].replace(/<\/?(\w+).*/,"$1"),!(f[j]||-1<"<p><img><br><li><hr>".search("<"+h+">"))){e=c[j];g=-1;if(!/^<\//.test(e))for(e=j+1;e<d;e++)if(!f[e]&&c[e]=="</"+h+">"){g=e;break}-1==g?n=i[j]=!0:f[g]=!0}if(!n)return a;j=0;return a=a.replace(b,function(a){a=i[j]?"":a;j++;return a})}
function o(a){a=(a.match(/~/g)||[]).length;return Array(a+2).join("~")}function w(a){if(/^lang-/.test(a))return a;var b="c_"+a,c=N[b];if(c)return c;if(P[b])return null;P[b]=!0;b=k.length;0<b&&RegExp("^"+k[b-1]).test(a)?k[b-1]=a:k.push(a);I.trigger();return null}function E(a,b,c){a=a.replace(K,function(a,c,d){return b+c+b+d});return a.replace(H,function(a,b){return c+b+c})}function f(a,b,c){var a=a.replace(RegExp(b+"([a-z0-9#+.-]+)"+b+"(\\s*?<pre)","gi"),function(a,b,c){a=w(b);return!a?c:c+" class='"+
a+" prettyprint-override'"}),d;return a.replace(RegExp("("+c+"([a-z0-9#+.-]+)"+c+")|(<pre><code>)","gi"),function(a,b,c){if(b)return d=c,"";if(!d)return a;b=w(d);return!b?a:"<pre class='"+b+" prettyprint-override'><code>"})}function y(a){function b(){h.animate({height:e.height()-g})}function c(a){if(e)a();else if(!n){n=!0;var d=l.offset();g=d.top-$("#wmd-button-row"+j).offset().top-$("#wmd-button-row"+j).outerHeight()-5;f=$("#wmd-help-button"+j);var p=f.offset().left+f.outerWidth(),d=d.left,k=l.outerWidth()+
d,k=Math.max(p,k);i={right:p-k,width:k-d,top:$("#wmd-button-row"+j).outerHeight()+5};f.addClass("active-help");h=$("<div style='clear:both' />").insertBefore(l);e=$('<div id="mdhelp'+j+'" class="mdhelp"><ul id="mdhelp-tabs'+j+'" class="mdhelp-tabs"><li /></ul></div>').find("li").addSpinner().end().css(i).insertAfter(f);b();$.get("/posts/markdown-help",{postfix:j}).done(function(c){e.remove();e=$(c).insertAfter(f).css(i);$("#mdhelp-tabs"+j).delegate("li:not(:last-child)","click",function(){var a=$(this).hasClass("selected");
e.find(".mdhelp-tab").hide();$("#mdhelp-tabs"+j+" li").removeClass("selected");if(!a&&($("#"+$(this).attr("data-tab")).show(),$(this).addClass("selected"),a=$(this).attr("data-buttons")))for(var a=a.split(","),c=0;c<a.length;c++){var d=$("#wmd-"+a[c]+"-button"+j);d.is(":animated")||d.animate({top:-15},400).animate({top:0},400).animate({top:-8},300).animate({top:0},300).animate({top:-4},200).animate({top:0},200).animate({top:-2},100).animate({top:0},100).animate({top:-1},50).animate({top:0},50)}b()});
n=!1;a()})}}function d(){k=!0;c(function(){f.addClass("active-help");e.show();b()})}var h,e,g,f,i,n=!1,j=(a||{}).postfix||"",l=$("#wmd-input"+j),k=!1;this.toggle=function(){e&&e.is(":visible")?(e.hide(),h.animate({height:0}),f.removeClass("active-help")):d()};this.showOnce=function(){k||d()}}if(!StackExchange.MarkdownEditor){var F,h,n=[],a=function(a){function b(a){return"facebook.stackoverflow.com"===a?"stackoverflow.com":a}function c(b){window.apiCallbacks[b]||(window.apiCallbacks[b]=function(c){if(c)if(c.error_message)/^No site found/.test(c.error_message)&&
(l["s_"+b]=!0);else if(c.items){for(var c=c.items,d=c.length,e=0;e<d;e++){var h=c[e];g[b+"|"+h.question_id]=h.title}a&&a()}});return'apiCallbacks["'+b+'"]'}function d(a,c){if(b(a)===f)return!0;var e=k[a];e||(e=k[a]={count:0,ids:{}});if(e.ids[c])return!0;if(e.count>=o)return!1;e.count++;return e.ids[c]=!0}var e=/<a href="((\S+)\/q(?:uestions)?\/(\d+)(?:|\/\S*?))">\1<\/a>/g,h=window.location.hostname.toLowerCase(),f=b(h),g={},i={},j={},n=StackExchange.helpers.DelayedReaction(function(){var a=!1,d;for(d in j)if(j.hasOwnProperty(d)){var e=
c(d),h;30<j[d].length?h=j[d].splice(0,30).join(";"):(h=j[d].join(";"),delete j[d]);a=!0;$.ajax({url:"http://api.stackexchange.com/2.0/questions/"+h+"?pagesize=30&key=6AU78DZ)GcdjNjAszYmTLQ((&filter=!6G7RPxWUNTleV&site="+b(d),crossDomain:!0,jsonpCallback:e,dataType:"jsonp"});break}a&&n.trigger()},1E3,{sliding:!0}),l={};window.apiCallbacks={};var k={},o=/^meta\./.test(f)?40:10;return function(a){k={};return a.replace(e,function(a,c,e,h){e=e.toLowerCase().replace(/^http:\/\//,"");if(/[^a-z0-9.]/.test(e)||
!d(e,h))return a;var k=g[e+"|"+h];if(k)h=k;else{if(k=!i[e+"|"+h]){k=b(e);if(k===f)k=!1;else if(l["s_"+k])k=!0;else var p=/^meta\./.test(f),k=f==="meta."+k||!p&&"meta."+f===k||p&&"meta.stackoverflow.com"==k||"meta.stackoverflow.com"===f?!1:!0;k=!k}k&&(i[e+"|"+h]=!0,(k=j[e])||(k=j[e]=[]),k.push(h),n.trigger());h=null}return!h?a:'<a href="'+c+'">'+h+"</a>"})}}(m),b=$.Callbacks();StackExchange.MarkdownEditor=function(c){var d=c.postfix||"";F=$("#hlinks a").filter(function(){return"main"==$(this).text()}).attr("href");
h=!!F;var f=new Markdown.Converter,i=f.hooks;i.addNoop("preSafe");i.chain("postConversion",a);i.chain("postConversion",function(a){return i.preSafe(a)});i.chain("postConversion",x);i.chain("postConversion",A);i.chain("postConversion",q);i.chain("postConversion",l);c.enableSections&&(i.chain("preConversion",g),i.chain("postConversion",e));var k=new y({postfix:d}),o={helpButton:{handler:k.toggle}};c.noCode&&(o.strings={code:"Preformatted text <pre><code> Ctrl-K",codeexample:"enter preformatted text here"});
f=new Markdown.Editor(f,d,o);f.hooks.chain("postBlockquoteCreation",j);StackExchange.options.disableImageUploads||f.hooks.set("insertImageDialog",StackExchange.imageUploader.uploadImageDialog);b.fire(f,c.postfix);var m=$("#wmd-preview"+d);f.hooks.chain("onPreviewRefresh",function(){m.trigger("wmdrefresh")});n.push(f);f.run();if(c.immediatelyShowMarkdownHelp)k.showOnce(c);else if(c.autoShowMarkdownHelp)$("#wmd-input"+d).one("focus",function(){k.showOnce(c)});f.disableSubmission=function(){$("#submit-button"+
d).attr("disabled","disabled");StackExchange.navPrevention.stop()};return f};StackExchange.MarkdownEditor.creationCallbacks=b;StackExchange.MarkdownEditor.refreshAllPreviews=m;var c=[],d;StackExchange.MarkdownEditor.sanitizeHtml=C;var i=/^(<\/?(b|blockquote|code|del|dd|dl|dt|em|h1|h2|h3|i|kbd|li|ol|p|pre|s|sup|sub|strong|strike|ul)>|<(br|hr)\s?\/?>)$/i,Q=/^(<a\shref="((https?|ftp):\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\stitle="[^"<>]+")?\s?>|<\/a>)$/i,v=/^(<img\ssrc="(https?:\/\/|\/)[-A-Za-z0-9+&@#\/%?=~_|!:,.;\(\)]+"(\swidth="\d{1,3}")?(\sheight="\d{1,3}")?(\salt="[^"<>]*")?(\stitle="[^"<>]*")?\s?\/?>)$/i;
StackExchange.MarkdownEditor.balanceTags=A;var N={},P={},k=[],I=StackExchange.helpers.DelayedReaction(function(){0!=k.length&&($.ajax("/api/tags/"+encodeURIComponent(k.join(";"))+"/syntax-highlight",{cache:!0}).done(function(a){var b=!1,c;for(c in a)a.hasOwnProperty(c)&&(N["c_"+c]=a[c],b=!0);b&&(StackExchange.MarkdownEditor.refreshAllPreviews(),styleCode())}),k=[])},2E3,{sliding:!0}),K=/<\!-- language: ([a-z0-9#+\-.]+) --\>(\s*?<pre>\s*?<code>)/gi,H=/<\!-- language-all: ([a-z0-9#+\-.]+) --\>/gi}})();
StackExchange.editor=function(){var m=function(j){var j=j||{},m=j.postfix||"",r=j.heartbeatType,g=j.bindNavPrevention,e=$("#post-form"+m),l=$("#wmd-input"+m),x;x=$("#title, #edit-comment, #m-address, .edit-comment");m=x.add(".tag-editor input");e.submit(function(){if(window.postSubmitCallback&&!window.postSubmitCallback())return!1;x.each(function(){StackExchange.helpers.hideHelpOverlay($(this))});StackExchange.helpers.disableSubmitButton(e);StackExchange.navPrevention.stop();return!0});$(".original-question").not(".processed").TextAreaResizer();
l.not(".processed").TextAreaResizer();l.typeWatch({highlight:!1,wait:5E3,captureLength:5,callback:styleCode});var C=new StackExchange.MarkdownEditor(j);if(r){var D=j.discardSelector?$(j.discardSelector):null;StackExchange.cardiologist.addHeart(r,l,C,D)}if("ask"==r||"answer"==r){var A=l.add(m),o=function(){StackExchange.helpers.loadTicks(e);A.unbind("keydown",o);return!0};A.bind("keydown",o)}g&&StackExchange.navPrevention.init(l);e.find(".wmd-preview").click(function(){l.focus()});StackExchange.helpers.bindHelpOverlayEvents(x);
0==$("#ask-error-container").length&&$("#title").is("input")&&$("#title").focus();if(j.oncreated)j.oncreated(C);if(j.discardSelector&&("ask"==r||"answer"==r)){var w=$(j.discardSelector);w.click(function(e){e.preventDefault();confirm("Are you sure you want to discard your draft?")&&($("#title").val(""),$("#question-suggestions").empty(),$("#wmd-input-42").val(""),$("#wmd-preview-42").html(""),e=$("#tagnames"),0<e.length&&e[0].func_clear&&e[0].func_clear(),l.val(""),C.refreshPreview(),$.post("/post/discard-draft",
{fkey:StackExchange.options.user.fkey,postType:r},function(){$("#draft-saved").hide();$("#draft-discarded").show();var e=null,e=function(){$("#draft-discarded").hide();$("#title").unbind("keypress",e);l.unbind("keypress",e)};$("#title").bind("keypress",e);l.bind("keypress",e)}),w.hide())})}};return{init:m,initIfShown:function(j){var q=(j||{}).postfix||"";0!=$("#wmd-preview"+q).length&&("-42"!==q||0===$("#answer-from-ask").length)&&0===$("#show-editor-button"+q).length?(m(j),StackExchange.editor.finallyInit||
(StackExchange.editor.finallyInit=function(){})):StackExchange.editor.finallyInit=function(){m(j)}}}}();
StackExchange.cardiologist=function(){function m(e){e="number"===typeof e?e:1E3*(D+A);E&&(e=Math.max(e,6E3-((new Date).getTime()-E)));f&&clearTimeout(f);f=setTimeout(j,e)}function j(){f=null;if(!l.length){var h;l=[];e&&!e.isDisabled&&30>e.beatCount&&l.push(e);for(var j=0;j<g.length;j++)h=g[j],h!=e&&!h.isDisabled&&30>h.beatCount&&l.push(h);D=Math.max(15,Math.min(45,60/(l.length||1)))}l.length?(h=l.shift(),h.checkActive()?h.beat():m()):m()}function q(){}function r(e){var f=[];$.get("/questions/"+e,
function(a){a=$(a);a.find("div.answer").each(function(){var a=this.id.substring(7);0==$("#answer-"+a).length&&f.push(this.id)});if(0<f.length){var b="#"+f.join(",#"),a=a.find(b),b=$("div.answer:last");0==b.length&&(b=$("#answers-header"));a.hide();b.after(a);a.fadeIn("slow");b=$("div.answer").length;$(".subheader h2").text(b+" Answer"+(1<b?"s":""));StackExchange.vote.init(e);StackExchange.comments.init({post:a})}StackExchange.notify.close(w);o=!1},"html")}var g=[],e,l=[],x,C,D=45,A=0,o=!1,w=-2,E,
f,y={ask:function(e){if(e.relatedQuestions){var f=$("#how-to-format"),a=e.relatedQuestions!=C;a&&f.hide();f.empty().append("<h4>Similar Questions</h4>"+e.relatedQuestions);a&&showFadingHelpText(f);C=e.relatedQuestions}},answer:function(e,f){if(e&&!o)if(e.disableEditor)StackExchange.notify.show("This question has been "+e.message+" - no more answers will be accepted.",w),o=!0;else{var a=parseInt(e.message);0<a&&(StackExchange.notify.show(a+" new answer"+(1==a?" has":"s have")+' been posted - <a id="load-new-answers">load new answers.</a>',
w),o=!0,$("#load-new-answers").click(function(){r(f.postId)}))}},edit:function(e){e&&e.message&&StackExchange.notify.getMessageText(w)!=$("<span />").html(e.message).text()&&(StackExchange.notify.close(w),StackExchange.notify.show(e.message,w))}};q.prototype={activate:function(){e=this;this.isActive||(this.isActive=!0,this.beatCount=0,g.push(this),1===g.length&&m())},checkActive:function(){if(!this.isActive||this.isDisabled)return!1;return!this.jTextarea.closest("body").length?(delete this.jTextarea,
this.isDisabled=!0,!1):!0},beat:function(e){var f=this,a={type:"POST",url:"/posts/"+this.postId+"/editor-heartbeat/"+this.type,dataType:"json",data:{}};e||(a.success=function(a){f.success(a)},a.error=function(){f.error()},a.complete=function(){f.complete()});if(this.shouldSendDraft()){var b={text:this.jTextarea.val()};"ask"===this.type&&(b.title=$("#title").val(),b.tagnames=$("#tagnames").val(),b.answertext=$("#wmd-input-42").val());if(!x||x.heart!==this||x.title!==b.title||x.tagnames!==b.tagnames||
x.text!==b.text||x.answertext!==b.answertext)a.data=b,x={heart:this,title:b.title,tagnames:b.tagnames,text:b.text,answertext:b.answertext}}if(e&&!("text"in a.data))return $.Deferred().resolve().promise();this.revisionGuid&&(a.data.clientRevisionGuid=this.revisionGuid);"answer"===this.type&&(e=$("#answers-header .answers-subheader h2").text().replace(/ answers?/i,"")||"0",a.data.clientCount=e);E=(new Date).getTime();return $.ajax(a).promise()},shouldSendDraft:function(){return"edit"!==this.type&&e===
this},success:function(e){y[this.type](e,this);e.disableEditor&&(this.editor.disableSubmission(),this.isDisabled=!0);e.draftSaved&&F(this.jTextarea,this.discardDraftLink);this.beatCount++;A=0},error:function(){$("#draft-saved").hide();e===this&&l.unshift(this);A=(new Date).getTime()%100/10},complete:function(){m()}};var F=function(e,f){var a=$("#draft-saved"),b=function(){a.text("draft saved").fadeIn("fast")};a.is(":visible")?a.fadeOut("fast",b):b();f&&f.removeClass("dno").show();var c=function(a){if(115!=
a.which||!a.ctrlKey||a.shiftKey||a.altKey)e.unbind("keypress",c),$("#draft-saved").fadeOut("fast")};e.bind("keypress",c);$("#draft-discarded").hide()};return{addHeart:function(e,f,a,b){var c=new q,d;c.type=e;c.jTextarea=f;c.discardDraftLink=b;switch(e){case "ask":d=0;break;case "answer":d=location.href.match(/\/questions\/(\d+)/i)[1];break;case "edit":d=$("#post-id").val()||f.closest(".question, .answer").find(".vote input").val(),e=f.closest(".inline-post"),b=null,0<e.length&&(b=e[0].action.split("/").pop()),
b||(b=$("#client-revision-guid").val()),c.revisionGuid=b}c.postId=d;c.editor=a;f.keypress(function(){c.activate()})},ensureDraftSaved:function(f){!e||!e.checkActive()?f():e.beat().done(f)},beatASAP:function(){m(1)},notifiedOfNewAnswer:function(){o=!0},isHeartBeating:function(){if(null==g)return!1;for(var e=0;e<g.length;e++)if(!0==g[e].checkActive())return!0;return!1}}}();
StackExchange.navPrevention=function(){var m,j,q=function(){var e=!1;m.each(function(g){e=e||$(this).val()!==j[g]});return e},r=function(e){window.onbeforeunload=e?function(){if(m&&q())return e}:null},g=function(){r("You have started writing or editing a post.")};return{init:function(e){m=e.one("keypress",g);j=[];e.each(function(){j.push($(this).val())})},start:function(){m&&g()},stop:function(){m&&(m.unbind("keypress",g),r(null),m=null)},confirm:function(e){return m&&q()?confirm(e):!0}}}();
(function(m){function j(j){g=m(j.data.el);g.blur();l=j.clientY+document.documentElement.scrollTop;e=g.height()-l;g.css("opacity",0.25);m(document).mousemove(q).mouseup(r);return!1}function q(j){var m=j.clientY+document.documentElement.scrollTop,q=e+m;l>=m&&(q-=5);l=m;q=Math.max(x,q);g.height(q+"px");q<x&&r(j);return!1}function r(){m(document).unbind("mousemove",q).unbind("mouseup",r);g.css("opacity",1);g.focus();e=g=null;l=0}var g,e,l=0,x=32;m.fn.TextAreaResizer=function(){return this.each(function(){g=
m(this).addClass("processed");e=null;m(this).parent().append(m('<div class="grippie"></div>').bind("mousedown",{el:this},j));var l=m("div.grippie",m(this).parent())[0];l.style.marginRight=l.offsetWidth-m(this)[0].offsetWidth+"px"})}})(jQuery);"use strict";
StackExchange.imageUploader=function(){return{uploadImageDialog:function(m){var j="upload-iframe-"+(new Date).getTime(),q=$("<div style='top: 50%; left: 50%; display: block; padding: 10px; position: fixed; width:400px; z-index:1001' class='wmd-prompt-dialog'><div style='position: absolute; right: 20px; bottom: 5px; font-size: 10px;'>image hosting by <a title='imgur: the simple image sharer' href='http://imgur.com'>imgur.com</a></div><p><b>Insert an image</b></p><p style='padding-top: 10px;'><a href='#' class='wmd-mini-button selected' id='upload-image-button'>from my computer</a><a href='#' class='wmd-mini-button' id='upload-url-button'>from the web</a></p><iframe id='"+j+
"' style='display:none;' src='about:blank' name='"+j+"'/><form action='/upload/image' method='post' enctype='multipart/form-data'><input type='hidden' name='fkey' value='"+StackExchange.options.user.fkey+"' /><div style='position: relative;height: 40px;' id='upload-file-input'><img src='http://i.imgur.com/GKc7H.png' height='15px' width='15px' style='vertical-align:middle;margin-right:6px;'><input type='file' name='filename' id='filename-input' value='browse' style='border:0; vertical-align:middle;'></div><div id='upload-url-input' style='display:none;height:40px;'><input type='input' name='upload-url' value='' style='width: 250px;'></div><p id='upload-message' style='padding-top: 4px; margin:0; line-height: 16px;'></p><div class='ac_loading' id='image-upload-progress' style='background-color: transparent; display:none;'>Uploading ...</div><input type='submit' value='Upload' style='width: 7em; margin: 10px;'><input type='button' value='Cancel' id='close-dialog-button' style='width: 7em; margin: 10px 10px 20px;'></form></div>"),
r=function(e){27===(e.charCode||e.keyCode)&&g(null)},g=function(e){$("body").unbind("keydown",r);q.remove();m(void 0==e?null:e);return!1};top.setTimeout(function(){q.appendTo("body");$("#close-dialog-button").click(function(){g()});var e=$("#upload-image-button"),l=$("#upload-url-button"),m=$("#upload-url-input"),C=m.parent(),D=$("#upload-file-input");m.remove().show();var A=function(){$("#upload-message").text("click browse to choose an image from your computer")};A();e.click(function(){l.removeClass("selected");
e.addClass("selected");A();m.remove();C.prepend(D);return!1});l.click(function(){e.removeClass("selected");l.addClass("selected");$("#upload-message").text("paste the URL of your image above");C.prepend(m);m.find("input").focus();D.remove();return!1});e.add(l).keypress(function(e){(13===e.which||32===e.which)&&$(this).click()});$("#"+j);q.find("form").submit(function(){$("#upload-message").hide();$("#image-upload-progress").show();this.target=j;window.closeDialog=g;window.displayUploadError=function(e){$("#image-upload-progress").hide();
$("#upload-message").css({color:"red",fontWeight:"bold"}).show().text(e)};return!0});q.center();$("body").keydown(r);$("#filename-input").focus()},0);return!0}}}();
